### ISSUE TITLE
Clear documentation to how to receive cloudevents 

### ISSUE THREAD

**Issue by Justin2997** [cloudevents/sdk-javascript#11]
I am opening this issue as a question but also for proposing my help if you need. I will like to see a receive section in the readme as there is in the golang sdk : https://github.com/cloudevents/sdk-go#working-with-cloudevents

If you think is a good idea I can look into this.

**Comment by fabiojose** [comment]
Off course! It's an amazing idea!

@justin2997

Please perform the PR!

**Comment by Justin2997** [comment]
I think that will be useful to as something like this: https://github.com/GoogleCloudPlatform/functions-framework-nodejs#enable-cloudevents in the readme. We can add other languages too. That will make it more centralize in the repo to receive and send CloudEvent.

**Comment by fabiojose** [comment]
LGTM

**Comment by jthomas** [comment]
This is a great idea. I came to this repo looking for the exact same thing.... I'd like to have both the ability to decode an incoming cloudevents message (with validation) manually using the SDK and then have the automatic HTTP listener (mirroring the Go SDK example) where I can just register the event processing callback.

**Comment by Justin2997** [comment]
@jthomas  I will do a PR. I need to test it first.

**Comment by fabiojose** [comment]
A way to receive event is available now:

Check it out [here](https://github.com/cloudevents/sdk-javascript#receiving-events)
