### ISSUE TITLE
Add helio-frota as collaborator 

### ISSUE THREAD

**Issue by helio-frota** [cloudevents/sdk-javascript#114]
Hi, I'd like to become a collaborator for this repository as I'm working with Node.js at Red Hat.
And helping with some FaaS efforts.

Thanks.

**Comment by grant** [comment]
Sounds good.
All GitHub collaborators are members of the cloudevents GitHub org, SDK Maintainers team.
https://github.com/orgs/cloudevents/teams/sdk-maintainers

To be a part of the GitHub org, you need to ask Dug on the CNCF Slack. Probably best to do that during the work week.

**Comment by fabiojose** [comment]
@duglin could you add @helio-frota as sdk-maintainers? Thanks in advance.

**Comment by duglin** [comment]
Done

**Comment by helio-frota** [comment]
@fabiojose @duglin Thank you!
