### ISSUE TITLE
Suggestion of Node.js versions on CI based on package maintenance group practices

### ISSUE THREAD

**Issue by helio-frota** [cloudevents/sdk-javascript#119]
Hi,

Based on recent comments [here](https://github.com/cloudevents/sdk-javascript/pull/106#discussion_r418337403) and [here](https://github.com/cloudevents/sdk-javascript/pull/106#discussion_r419501709)  

I found that may be worth to open this issue. 

Directly to the point, the idea is to avoid changing Node.js LTS versions over the time by using `lts/*` and able to include specific versions (current and/or deprecated) as can be seen [here](https://github.com/nodeshift/nodeshift/blob/master/.travis.yml#L3-L5)

Here is an article with information about that approach:

https://medium.com/@nodejs/choosing-the-node-js-versions-for-your-ci-tests-hint-use-lts-89b67f68d7ca

**Comment by grant** [comment]
Adding `lts/*` LGTM.

**Comment by lance** [comment]
I like that it will always pick up the most recent LTS version. However, it won't automatically get version 10, which means in `.travis.yaml` we'd still need to have both `10` and `lts/*` specified.

It _does_ buy us LTS testing the moment a new LTS version is released, which is nice. We'd just need to remember to add `12` once `14` is released.

**Comment by helio-frota** [comment]
> which means in .travis.yaml we'd still need to have both 10 and lts/* specified.

Yeah, still need to have 10. This is to remove the need of updating lts over time.

**Comment by lance** [comment]
@helio-frota can you speak closed? It looks like #106 took care of it, right?

**Comment by helio-frota** [comment]
@lance Sorry, I guess I'm not following your question.
The idea in this issue is just to change the hard-coded [12](https://github.com/cloudevents/sdk-javascript/blob/master/.travis.yml#L3) to `lts/*` in `.travis.yml`, all the other versions keep the same.

**Comment by lance** [comment]
@helio-frota OMG I'm sorry! I was making these comments while only half awake this morning using voice to text. It's a mess. I mean to say... would you mind updating #121 so that it doesn't build the backport branch, but keeps this suggested change?

**Comment by helio-frota** [comment]
@lance yup not a problem, PR updated :+1:

**Comment by helio-frota** [comment]
Closing... PR landed https://github.com/cloudevents/sdk-javascript/commit/c1fda94d25f84db097e75177b166c3f18f707dda
