### ISSUE TITLE
develop branch and npm package behind

### ISSUE THREAD

**Issue by csantanapr** [cloudevents/sdk-javascript#12]
There are 2 PRs that are already merged.

PR #10 Changed JSON schema validator's options to remove warning: "$ref: key…
- is in the develop branch, not in master or released in npm registry

PR #8 Added missing 'source' getter on Spec02
- is in master branch but not released on npm registry

Can this 2 fixes be promoted to the npm registry?

Also trunk based development working on `master` branch seems to be more productive and adopted this days, why not just have 1 branch `master`?

**Comment by csantanapr** [comment]
For anyone hitting the same problem I created a branch with develop merged in master here is what to put in your `package.json`
```json
{
  "dependencies": {
    "cloudevents-sdk": "csantanapr/cloudevents-sdk-javascript#tempfix-12",
  }
}
```

**Comment by fabiojose** [comment]
@csantanapr sorry about this little mess!

Now, the things are good again!

https://www.npmjs.com/package/cloudevents-sdk/v/0.2.1
