### ISSUE TITLE
Modify CI to also build the backport branch(es)

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#121]
The Travis-CI configuration should be modified so that it also runs for the `v1.x.y` branches.

@helio-frota maybe you can tackle this and https://github.com/cloudevents/sdk-javascript/issues/119 in a single PR?

**Comment by helio-frota** [comment]
@lance yup, PR sent https://github.com/cloudevents/sdk-javascript/pull/122

**Comment by helio-frota** [comment]
@lance this needs to be cherry-picked into v1.x.y when merged :+1:

**Comment by lance** [comment]
Adding `stalled` since branching is in question if not dead

**Comment by lance** [comment]
Closing for now. Will re-open if we end up needing to maintain version branches.
