### ISSUE TITLE
Consider adding a files section in package.json

### ISSUE THREAD

**Issue by helio-frota** [cloudevents/sdk-javascript#125]
Currently after install this module we are getting all these files and directories:

```console
CHANGELOG.md  CONTRIBUTING.md  ext  http  index.js  lib  LICENSE  
OLDOCS.md  package.json  README.md  test  v02  v03  v1
```

It would be good to add a `files` section in package.json to discard unneeded resources for end-user installations.

https://docs.npmjs.com/files/package.json#files

**Comment by grant** [comment]
Ideally we have a `src` directory.

**Comment by lance** [comment]
Landed in https://github.com/cloudevents/sdk-javascript/commit/f8a62b2843b12fe894201670770a00c034ab701d
