### ISSUE TITLE
How to test that an event is a cloud event?

### ISSUE THREAD

**Issue by doru1004** [cloudevents/sdk-javascript#150]
Hi,

I have been trying several ways to test that an event is a cloud event but I keep getting this error:

```
TypeError: Right-hand side of 'instanceof' is not an object
```

( or, when I don't get this error then the check return false when the event is a cloud event. )

I have installed CloudEvents via the npm install command (which installs v1.0.0 from what I can tell).

My code:

```shell
const { Cloudevent } = require('cloudevents-sdk/v1)
...
if (event instanceof Cloudevent) {...}
```

Is there some other way to test an object is a valid cloud event? Is this check different or fixed in the versions newer than the one NPM installs?

Thanks a lot!

**Comment by helio-frota** [comment]
Hi @doru1004 ,

I reproduced your issue here.
The good news is that the current code on master branch works fine:

```js
cat index.js
const { CloudEvent } = require("cloudevents-sdk");

const event = new CloudEvent();

if (event instanceof CloudEvent) {
    console.log(true)
}
```

```console
node index.js 
true
```

But I don't know when it will be published /cc @lance @fabiojose

**Comment by doru1004** [comment]
Thanks a lot for trying that out @helio-frota ! Will be waiting for the fix to be published. :)

**Comment by lance** [comment]
Hi @doru1004. We are hoping to have a 2.0.0 release out soon (hopefully this week, but that may stretch into early next week) with some nice, simplifying API changes, proper classes such as `CloudEvent`, and better IDE support. (You can see sample code on the [README](https://github.com/cloudevents/sdk-javascript#receiving-events)).

In the interim, if you are comfortable doing so, you can depend on a specific commit hash in your package.json. For example, to get what is basically the most up to date code, you can use this in your package.json: `"cloudevents-sdk": "cloudevents/sdk-javascript#fd99cb1"`. Hope this helps.

**Comment by doru1004** [comment]
Sounds great and I like the incoming API changes! This definitely helps! Thanks again for the quick replies @lance @helio-frota !
