### ISSUE TITLE
Eliminate specific version numbers from examples and docs to extent possible

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#160]
> In general, the version specific comments throughout these docs will have a short shelf life.

https://github.com/cloudevents/sdk-javascript/pull/141/files#r424509323

This is generally true. We should, as much as possible, find a way to eliminate these from the docs and examples except where it can't be avoided - e.g. providing a version number to an emitter to ensure that an event is transported via a specific spec version.

**Comment by lholmquist** [comment]
@lance i can take a look at this if it is still open?

**Comment by lance** [comment]
It's all yours @lholmquist :)

**Comment by grant** [comment]
Won't this version of the README/code be invalid when the spec reaches 2.0 and a user clones the old one?
