### ISSUE TITLE
Clarify and/or Separate Bindings and Formats Table

### ISSUE THREAD

**Issue by erikerikson** [cloudevents/sdk-javascript#166]
The table at https://github.com/cloudevents/sdk-javascript/tree/cf36a1578af4c482f9d41c1c97e98ab7634accf1#supported-specification-features lists both bindings and formats in the same table.   This is somewhat confusing and, unless these concerns are tangled in the codebase, potentially inappropriate.  If they are tangled, then I would expect the table to represent that explicitly.

I don't expect this is the highest priority but perhaps when it is time, this will serve as a placeholder for the PR?

**Comment by lance** [comment]
Agree it's not the highest priority, but you're right that conflating these two isn't idea. This markdown was shamelessly stolen from https://cloudevents.github.io/sdk-go/
