### ISSUE TITLE
How to have autocompletion?

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#169]
We need fantastic IDE documentation with inline documentation.

```js
import {CloudEvent} from 'cloudevents/v1';
const ce = new CloudEvent();
ce.
```

![image](https://user-images.githubusercontent.com/744973/82247245-ef2a6380-98fa-11ea-83a4-44723bac0827.png)

This requires https://github.com/cloudevents/sdk-javascript/issues/65

**Comment by lance** [comment]
@grant can you show more of the code here? How are you creating `ce`?

**Comment by grant** [comment]
```js
const ce = new CloudEvent();
```
Is how you create the `ce`.

**Comment by lance** [comment]
So, I guess I'm not clear on what should change, because this is possible today. Am I missing something?

![image](https://user-images.githubusercontent.com/15952/82269790-b0b79780-9940-11ea-9e6d-45508b44feb9.png)

**Comment by grant** [comment]
This is what I see in my editor (VS Code) after following the Usage section of the README:

![Screen Shot 2020-05-18 at 16 54 44](https://user-images.githubusercontent.com/744973/82270071-704c1f80-9928-11ea-9a8b-1bf777b21386.png)

Maybe the module isn't updated on npm, but I'd expect to see the experience you're getting when developing locally. I don't want to memorize the CloudEvent properties of course.

---

In the above picture, it looks like we're using typescript types (`: any`, `:CloudEvent`), which is good.

**Comment by lance** [comment]
No, the module is not published on npm with these changes yet. You should try from `master`.

**Comment by grant** [comment]
> No, the module is not published on npm with these changes yet. You should try from `master`.

OK. Got it. I'll keep this issue open until we publish to npm then. A user can't really build all npm dependencies from source of course.

**Comment by lance** [comment]
2.0.0 released today, including type definitions.
