### ISSUE TITLE
https://www.npmjs.com/package/cloudevents-sdk has 6 months old package

### ISSUE THREAD

**Issue by alexkhimich** [cloudevents/sdk-javascript#176]

**Comment by lance** [comment]
Hi @alexkhimich - we are [planning a 2.0 release](https://github.com/cloudevents/sdk-javascript/issues/127) and hope to have it out before the end of the month. It is a major change with lots of new features and a changed API, so it's not going quite as fast as we would like. But I agree! An updated is needed soon. In the meantime, if you are not running production code with this, you can refer to a commit hash on github in your package.json dependency. Check out the [npm docs](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) for more info if you are unfamiliar.

**Comment by lance** [comment]
2.0.0 was released today. Closing this. Please feel free to open any issues you have around the new API.
