### ISSUE TITLE
HTTP binding for binary format

### ISSUE THREAD

**Issue by playground-julia** [cloudevents/sdk-javascript#18]
The HTTP binding for binary formatted data currently does not follow the cloudevents/spec:
1. The event type, time, and schema url should not be required
2. the content-type should be json, but not cloudevents-json

Additionally, the config object should be copied because creating multiple bindings with the same config will override the content-type.

Fixed in issue #14.

**Comment by fabiojose** [comment]
Release in version [0.2.2](https://github.com/cloudevents/sdk-javascript/releases/tag/v0.2.2)

**Comment by playground-julia** [comment]
@fabiojose Tried to use the updated version and I noticed my changes for emitter_binary_0_2 didn't get merged in properly... The optional / required fields do not follow the spec but remain as they used to be.

**Comment by fabiojose** [comment]
Oh boy! I will check what gonna wrong!

**Comment by fabiojose** [comment]
Fixed! https://github.com/cloudevents/sdk-javascript/releases/tag/v0.2.3

**Comment by playground-julia** [comment]
Thanks, it works :)
