### ISSUE TITLE
Formatter should be static

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#195]
I noticed the formatter lives within the CloudEvent object.
```js
CloudEvent {
  spec:
   Spec1 {
     payload:
      { specversion: '1.0',
        id: '1234',
        time: '2020-05-28T20:46:18.970Z',
        source: '/some/source',
        type: 'example',
        datacontenttype: undefined,
        data: undefined,
        subject: undefined } },
  formatter: JSONFormatter {},
  extensions: [] }
```
This doesn't really make sense since we can have 1000 CloudEvent objects with the same formatter. 

Maybe it should be a static class/set of methods.

**Comment by lance** [comment]
I was thinking actually of removing it entirely from the class, along with the `format()` function. Instead, expose a top level `Formatter` class or `formatter()` function that takes a `CloudEvent` and formats it as JSON by default. But of course that would be a breaking change and require a version bump. Making it static is a good first step.

**Comment by lholmquist** [comment]
Probably going to hold off on this since it will be part of #226 

should we close?
