### ISSUE TITLE
Add TypeScript example to README

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#198]
There are a few different ways to use the API for TS users.

https://i.imgur.com/Vykt17Z.png
![image](https://user-images.githubusercontent.com/15952/83309050-3c011a80-a1d6-11ea-916e-0c4b8cd23dfc.png)

**Comment by grant** [comment]
Sounds good, although I'd expect a very simple example on the main README. It's pretty easy to discover new methods/types in TypeScript with awesome autocompletion.

We can link to a test for a more complicated sample showing every feature.

**Comment by BOLT04** [comment]
Hi @lance 👋. does this issue still apply to the current version of the SDK?
I noticed the package changed from `cloudevents-sdk` to `cloudevents`, so are those different usages still possible?

If it still applies and I could help just let me know 🙂

**Comment by lance** [comment]
Hey @BOLT04 thanks for the offer! Yes, the issue is still relevant. The `cloudevents-sdk` versions are all really old at this point, so really it's only `cloudevents` that is needed. Your contribution would be appreciated!

**Comment by BOLT04** [comment]
Awesome! I'll work on a PR this week 👍. Thanks 🙂
