### ISSUE TITLE
Rename Remaining .js Files to .ts

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#203]
It doesn't make sense to have some `.ts` files and some `.js` files in the repo. Although it will work, it is common to just rename the extension of all files to `.ts`.

**Comment by grant** [comment]
Hey @lance, do you have any thoughts around this?

**Comment by lance** [comment]
Hi @grant - I have actually been working on a complete rewrite of the entire module that does a lot more than just renaming the files to have a `.ts` extension. And it's 100% TS. I hope to have at least a draft PR of this ready this week.

**Comment by grant** [comment]
OK, sounds good. Thanks for the update @lance.
The rewrite sounds great and could solve lots of issues.

**Comment by lance** [comment]
I think we can probably consider renaming to 'cloudevents' as well with a 3.0.0 release

**Comment by grant** [comment]
https://www.npmjs.com/~lanceball now has full permissions for module `cloudevents`. Feel free to mirror previous versions/use that module for publishing.

**Comment by lholmquist** [comment]
> https://www.npmjs.com/~lanceball now has full permissions for module cloudevents.
Feel free to mirror previous versions/use that module for publishing.


was it actually decided that this module is changing names?  I thought that was an ongoing discussion in #215 ?

**Comment by lholmquist** [comment]
so getting back to the issue of #225,  if things are being re-written,  should we even worry about the test and just fix the issue now, so the users who reported the bug can do what they need to do and the typescript stuff will fix itself once the module is re-written?
