### ISSUE TITLE
CloudEvent constructor should accept inline extensions

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#209]
There is no way to create a `CloudEvent` instance using the constructor and have the extensions initialized there. For example, this is not valid, but should work.

```js
const ce = new CloudEvent({
  type: 'ex',
  source: '/path',
  extensions: {
    extension1: 'some data'
  }
});
```

**Comment by lholmquist** [comment]
@lance should the extensions property in your example, be an array of key:value pairs?

**Comment by lholmquist** [comment]
The reason I ask is because if you take a look at what is created after doing `const ce = new CloudEvent(...)`

The extensions property is a blank array

```
CloudEvent {
  spec: Spec1 {
    payload: {
      specversion: '1.0',
      id: '2b306349-ad39-4cd6-bb4e-1cddb02ecd0a',
      time: '2020-06-08T16:55:19.845Z',
      source: '/source',
      type: 'type',
      datacontenttype: undefined,
      data: undefined,
      subject: undefined
    }
  },
  formatter: JSONFormatter {},
  extensions: []
}
```


As soon as you call `addExtension(key, value)`, the value of thta property actually turns into an object:

```
CloudEvent {
  spec: Spec1 {
    payload: {
      specversion: '1.0',
      id: 'd1acd94e-aaec-4287-80f0-85fa4a57748b',
      time: '2020-06-08T16:57:45.721Z',
      source: '/source',
      type: 'type',
      datacontenttype: undefined,
      data: undefined,
      subject: undefined,
      'extension-key': 'extension-value',
      'extension-key1': 'extension-value1'
    }
  },
  formatter: JSONFormatter {},
  extensions: {
    'extension-key1': 'extension-value1',
    'extension-key': 'extension-value'
  }
}
```

Not sure what the correct answer should be here

**Comment by lance** [comment]
@lholmquist that was a bug that was fixed at the end of last week https://github.com/cloudevents/sdk-javascript/pull/202/files#diff-695048fccf8efadd88b77db776a94d06L84. It should be an object.

**Comment by lholmquist** [comment]
@lance yea,  i was just looking in the code and couldn't find that array, and just realized my example was using the version on npm.   :facepalm:
