### ISSUE TITLE
How to emit event to Knative broker?

### ISSUE THREAD

**Issue by akoenig** [cloudevents/sdk-javascript#22]
I have a Knative service which receives a CloudEvent from a Knative source. After processing this event I want to emit another CloudEvent to my Knative Eventing broker. Unfortunately, I'm having a hard time achieving this:

```typescript
const binding = new CloudEvent.bindings["http-binary0.2"]({
    method: "POST",
    url: "http://my-broker.default.svc.cluster.local/"
});
```

This configuration leads to communication timeouts. Any help on this is highly appreciated 🙂

**Comment by fabiojose** [comment]
Hi @akoenig 

Can you post the full source code?

**Comment by fabiojose** [comment]
@akoenig checkout this full example of how to emit CloudEvent using binary:

```js
var Cloudevent = require("cloudevents-sdk");

// The event
var cloudevent =
  new Cloudevent(Cloudevent.specs["0.2"])
    .type("com.github.pull.create")
    .source("urn:event:from:myapi/resourse/123")
    .data({
      dummy : "wow"
    });

// The binding configuration using POST
var config = {
  method: "POST",
  url   : "http://localhost:3000"
};

 // The binding instance
var binding = new Cloudevent.bindings["http-binary0.2"](config);


// Emit the event using Promise
binding.emit(cloudevent)
  .then(response => {
    console.log(response.data);
  }).catch(err => {
    console.error(err);
  });

```

**Comment by akoenig** [comment]
@fabiojose Thanks for your response. That was also exactly my code. My fault was that I had a wrong broker endpoint. So for posterity: When having a default Knative Eventing broker, just create the following `config`:

```js
const config = {
  method: "POST",
  url: "http://default-broker"
};
```

Closing. Thanks again 🙂
