### ISSUE TITLE
Passing custom headers through to http.request()

### ISSUE THREAD

**Issue by c-pius** [cloudevents/sdk-javascript#223]
When using HttpEmitter.send() method, how can I pass additional header arguments (e.g. meant for our infrastructure) that are passed through to the http.request() call? 

I tried to use
```javascript
const emitter = new HTTPEmitter({
    url: "https://foo.bar"
})

const event = ...

emitter.send(event, {
  headers: {
    customheader: "...",
    authorization: "Bearer ...."
  }
})
```

When debugging, it seemed like the passed headers are overwritten by the default headers.

https://github.com/cloudevents/sdk-javascript/blob/99bb88be00f832c58b5fdd467a8a2473830a6547/src/lib/bindings/http/emitter_binary.js#L56
translated to 
> const config = Object.assign(Object.assign({}, options), defaults);

**Comment by lance** [comment]
@c-pius it looks like the spread operator assignment is a bug. Thanks for reporting this.

**Comment by lholmquist** [comment]
I wonder if there are other places that are like this?

**Comment by lholmquist** [comment]
To answer my own question.  It looks like that is the only spot that the ordering was incorrect
