### ISSUE TITLE
CloudEvent should only allow [^a-z|0-9$] for extension names

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#228]
Per the spec's [naming conventions](https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention), attribute names should be all lower case, with nothing but a-z and 0-9 in the name. This module currently does not enforce that.

**Comment by lholmquist** [comment]
Is the "-" also allowed.  reading the spec,  it doesn't look like it.  If that is the case, then we will need to update the examples

**Comment by lance** [comment]
It is not allowed. Only alphanumeric characters.

> CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. Attribute names SHOULD be descriptive and terse and SHOULD NOT exceed 20 characters in length.

https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention

**Comment by lholmquist** [comment]
Should we make this a semver-major change then?

**Comment by lance** [comment]
> Should we make this a semver-major change then?

Yes - we will have a semver major release as soon as the typescript version lands, so it should land with that.
