### ISSUE TITLE
CloudEvent extensions should be restricted to types allowed in spec

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#229]
Currently an extension can have any value - e.g. it could be an object. However, the spec limits what value types an extension can have. See https://github.com/cloudevents/spec/blob/master/spec.md#type-system

**Comment by lholmquist** [comment]
Since the spec doesn't allow an Object, should we be throwing an error if someone passes in this:
```
new CloudEvent({
...
...
extension1: { key: value }
})
```
Or is this ok since it will get converted to a JSON before transmission.  basically,  should this test pass or fail:  https://github.com/cloudevents/sdk-javascript/blob/master/test/spec_1_tests.ts#L99

**Comment by lance** [comment]
That test should probably fail. We can't assume that the receiver will know that the value needs to be converted to an object. Since strings are valid value types, the user should use `JSON.stringify` before setting the extension.
