### ISSUE TITLE
emitter.send() drops datacontenttype header

### ISSUE THREAD

**Issue by c-pius** [cloudevents/sdk-javascript#240]
Not entirely sure on this but I think emitter.send() drops the datacontenttype header.

## structured
```javascript
const event = new CloudEvent({
    id: "4711",
    type: "foo",
    source: "bar",
    datacontenttype: "text/xml",
    data: "<xml>test</xml>"
});

emitter.send(event, { mode: "structured" }).then((response) => {
    console.log(`status: ${response.status} ${response.statusText}`)
}).catch(console.error)
```

received `content-type` header : "application/cloudevents+json"

received payload:
```json
{
    "data": "<xml>test</xml>",
    "specversion": "1.0",
    "id": "4711",
    "time": "2020-07-06T06:56:01.645Z",
    "source": "bar",
    "type": "foo"
}
```

## binary

```javascript
const event = new CloudEvent({
    id: "4711",
    type: "foo",
    source: "bar",
    datacontenttype: "text/xml",
    data: "<xml>test</xml>"
});

emitter.send(event, { mode: "binary" }).then((response) => {
    console.log(`status: ${response.status} ${response.statusText}`)
}).catch(console.error)
```

received `content-type` header = "application/json"

I assume the `datacontenttype` is dropped (not allowed in binary binding). But then the missing value is defaulted to application/json for the `content-type` header (seems correct from the [spec](https://github.com/cloudevents/spec/blob/v1.0/spec.md#datacontenttype)). However, the `content-type` header should be set to "text/xml" from the given `datacontenttype` value.

**Comment by lance** [comment]
For binary mode, the `ce-datacontenttype` header [MUST NOT](https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#311-http-content-type) be present in the message. But you are correct that the `content-type` header should be `text/xml` in this case.

For structured mode, the received payload should have the `datacontenttype` property. 

Thanks for reporting this.

**Comment by lance** [comment]
@lance I have been testing the binary mode transmission, and realized that you need to use `dataContentType`. If you do, your scenario should work. Still poking structured mode.

**Comment by lance** [comment]
@c-pius the module is working as expected for both binary and structured events. In both cases, the property on the `CloudEvent` object is `dataContentType`. I'm going to close this as not-a-bug. If you find additional problems please feel free to reopen or create a new issue.

**Comment by c-pius** [comment]
ah okay, sorry for the confusion. Will this change with the new release however? I was looking at the examples and that is actually where I got the all lowercase `datacontenttype` from 

https://github.com/cloudevents/sdk-javascript/blob/51035dc65b98ce7912d57a78d214612c05c5dc00/examples/typescript-ex/src/index.ts#L9

**Comment by lance** [comment]
@c-pius yes - the examples are previewing what will be coming in 3.0.0. You can track the release of that in [this issue](https://github.com/cloudevents/sdk-javascript/issues/241). We made this change to simplify marshaling/unmarshaling of `CloudEvent` objects, since the specification requires event attributes to be in all lowercase.
