### ISSUE TITLE
Prepare release 3.0.0

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#241]
The last release on the 2.x line was 2.0.2 on June 8. A major version bump after only one month isn't ideal, but it's probably good to get this out soonish so folks can start using it. If there is something you would like to see in the next release that is not listed here, please open a new issue or submit a pull request.

Edit: Updated July ~~24~~ __27__ with latest commits.

Changes since 2.0.2 release. (`git log v2.0.2..origin/master --oneline`)

a86cedc lib: remove unused event creation functions (#277)
3d82fb6 refactor: simplify ce version parsers (#274)
3c8273f lib: validate extension values (#251)
129ec48 refactor: combine v03 and v1 event interfaces, specs and schemas into single files(#270)
45850e3 chore: consolidate HTTP parsers and header maps into single files (#267)
1613595 chore: add vscode task JSON and GitHub issue/pr templates (#268)
a6124cc refactor: simplify parser logic and duplicated code (#269)
9ae32c7 lib: change Receiver#accept() to be static Receiver.accept (#271)
565f867 feat: use npm name cloudevents (#260)
4b54b27 feat: simplify validation logic/imports (#265)
4014da2 feat: remove unused plugins (#262)
a7c326b fix: do not require an HTTP body on incoming binary event messages
d866691 build(deps): bump lodash from 4.17.15 to 4.17.19 (#254)
cfde6d5 Add Copyright Date and Holder name (#257)
2ed5f84 fix: package.json & package-lock.json to reduce vulnerabilities (#253)
c496931 docs: clean up spec compliance table on README.md (#252)
84f1ed9 feat(src): add ext name validation (#246)
de6f0a2 docs(README): Update readme to mention that CloudEvents are read-only now (#248)
13bcdb4 fix: upgrade uuid from 8.1.0 to 8.2.0 (#250)
8e79fdc build(deps-dev): bump standard-version from 7.1.0 to 8.0.1 (#247)
c7a8477 feat(src):  A CloudEvent should be readonly but provide a way to augment itself. (#234)
dca2811 test: inplement the cucumber conformance tests from cloudevents/spec (#238)
90a9984 chore: bump GH stale action to v3 (#243)
51035dc fix: ensure that the HTTP receiver sanitizes headers in accept() (#239)
d65b013 chore(actions): don't auto-close stale issues and pull requests (#235)
25077a9 fix: upgrade uuid from 8.0.0 to 8.1.0 (#220)
276b810 BREAKING CHANGE(lib): rewrite in TypeScript (#226)
060b21b fix: parse method mutating its input (#231)
5ab8164 chore: adds the return type for the extensions (#221)
850e893 docs(README): fix wrong order of arguments in the accept example (#224)
7012433 chore: webpack should publish to bundles not _bundles (#227)
99bb88b examples: add a WebSocket example (#218)
8b2725b feat: introduce browser support (#201)
0378f4c feat: pass extension into the constructor. (#214)
dcb3c4e chore: Update examples to use the latest sdk version(2.0.2) (#206)
4265281 feat: add types to package.json (#216)
44b791b docs: generate api documentation as a GitHub workflow (#217)
ed1d328 docs: Update references of specific versions to use Latest Supported. (#211)

**Comment by lance** [comment]
I would like for #228 and #229 to land first - at a minimum.

**Comment by lholmquist** [comment]
I think #233 should also land before we do the release

**Comment by lance** [comment]
> I think #233 should also land before we do the release

My mistake - totally overlooked that. Yes of coruse!

**Comment by lholmquist** [comment]
Also #198 might be a good candidate

**Comment by grant** [comment]
Also going through the process to fix #215 seems appropriate when releasing.

**Comment by lholmquist** [comment]
https://github.com/cloudevents/sdk-javascript/pull/248 should also be part of 3.0

**Comment by lance** [comment]
We should probably start planning for this release to ship next week if possible. Before that, I would like the following PRs to land. Any objection @lholmquist / @grant?

* https://github.com/cloudevents/sdk-javascript/pull/271 - lib: change Receiver#accept() to be static Receiver.accept
* https://github.com/cloudevents/sdk-javascript/pull/270 - refactor: combine v03 and v1 event interfaces, specs and schemas into single files 
* https://github.com/cloudevents/sdk-javascript/pull/269 - refactor: combine all parsers into a single file
* https://github.com/cloudevents/sdk-javascript/pull/268 - chore: add vscode task JSON and GitHub issue/pr templates
* https://github.com/cloudevents/sdk-javascript/pull/267 - chore: consolidate HTTP parsers and header maps into single files
* https://github.com/cloudevents/sdk-javascript/pull/251 - lib: validate extension values

**Comment by lholmquist** [comment]
@lance No objections here,  and I think all those PRs have approvals and are ready to land.

**Comment by lholmquist** [comment]
All those listed pr's have merged except for #251 which has moved back to draft

**Comment by lance** [comment]
@lholmquist awesome - thanks! Maybe on Monday we can finish up #251 and head down the release road.

**Comment by lance** [comment]
Version 3.0.0 has been released as `cloudevents`
