### ISSUE TITLE
Proposal to change npm module name to 'cloudevents'

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#242]
Since [renaming the module has been an area of disagreement](https://github.com/cloudevents/sdk-javascript/issues/215) in this community, I propose we resolve this with a vote.

Currently the module is named `cloudevents-sdk`, however Grant has proposed changing this to simply `cloudevents` and has provided the `cloudevents` namespace on NPM. We have an upcoming 3.0.0 release which would be the appropriate time to make this change if voted on and approved.

Because there is no way to just change a module name and have things "just work", changing the name of the module would be a breaking change, requiring users to modify their existing package.json files. There are a couple of things that would need to happen in addition to simply renaming and publishing the module to npm.

1. Deprecate all current versions with a warning so that when they are installed by existing projects. `npm deprecate cloudevents-sdk@2.0.2 "WARNING: This module has been renamed to 'cloudevents'. Please install it instead. See https://cloudevents/sdk-javascript for more information."`
2. Update README with this same information

For votes in favor of renaming, please react to this issue description with :+1:. Those opposed, please react to this issue with :-1:.

Only votes on the issue description itself are counted. Please use additional comments to discuss pros/cons/concerns/etc. Thanks!

**Comment by helio-frota** [comment]
Additional comments: 
1) I agree this module is not an SDK, it is a library.
2) I agree that, at that time, was not good to change, but now the project has an opportunity frame/window to be changed.

**Comment by loopingz** [comment]
If we rename the module, I think it would be good to provide script to use with jscodeshift.
So either reuse stuff like this: https://github.com/jurassix/refactoring-codemods

or custom jscodeshift template, so people can just run `npx jscodeshift -t cloudevents-sdk-2.0-3.0`
```
const util = require("util");
// Update packages
const packagesReplaceMap = {
  "cloudevents-sdk": { pkg: "cloudevents" }
};

// Update package.json?

export default function transformer(fileInfo, api, options) {
  const j = api.jscodeshift;
  // eslint-disable-next-line global-require, import/no-dynamic-require
  const printOptions = options.printOptions || {};
  let root = j(fileInfo.source);

  // Replace all imports
  for (let i in packagesReplaceMap) {
    root
      .find(j.ImportDeclaration, {
        source: { value: i }
      })
      .replaceWith(path => {
        const { node, value } = path;
        value.source.value = packagesReplaceMap[i].pkg || i;
        return node;
      });
  }

  return root.toSource(printOptions);
}
```
This is a draft not final version, I can work on it if we think it is a good idea

**Comment by lance** [comment]
@loopingz this is good - but since the API has also changed, I wonder how tricky it will be

**Comment by grant** [comment]
I think the votes are in, thanks for organizing @lance 👍 
9 👍 
3 👎 
as of July 23, 2020.

Want to close this and resume in https://github.com/cloudevents/sdk-javascript/issues/215? I've created a PR.

**Comment by lance** [comment]
Closing. Fixed in https://github.com/cloudevents/sdk-javascript/pull/260
