### ISSUE TITLE
HTTPReceiver throws when data attribute is null or undefined

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#258]
I'm seeing multiple issues when trying to using this library and testing with a `cURL` request.

These are the issues:

- `TypeError: no cloud event detected`
  - Then I added CE headers. I would assume I'd still be able to accept CloudEvents even if it was missing a header.
- `TypeError: payload is null or undefined`
  - How do you specify this? What do you mean? I tried adding a HTTP body with no luck.

I'd expect this module to simply extract the CloudEvent from a Node HTTP request and not fuss around too much! It's easier to just not use the SDK and just inspect the headers.

```js
// CloudEvents Setup
const {HTTPReceiver} = require("cloudevents-sdk");
const receiver = new HTTPReceiver();

/**
 * Parse headers and body from HTTP request.
 */
exports.extractCloudEvent = function(req) {
  return receiver.accept(req.headers, req.body);
}
```

It's easier to just not use the SDK and parse the HTTP headers manually.

**Comment by grant** [comment]
Here's an example request that I would expect to work:

```sh
curl \
-H 'ce-id: projects/serverless-com-demo/logs/cloudaudit.googleapis.com%2Fdata_access-4pajkbeh8mwi159545fe7504177593' \
-H 'ce-type: com.google.cloud.auditlog.event' \
-H 'ce-specversion: 1.0' \
-H 'ce-subject: storage.googleapis.com/projects/_/buckets/test-demo_cloudbuild/objects/source/1595457496.641377-d046ef5b652b4da892a9354aa2ebfcf4.tgz' \
-H 'ce-dataschema: type.googleapis.com/google.logging.v2.LogEntry' \
-H 'ce-time: 2020-07-22T22:38:24.177593990Z' \
-H 'ce-source: //storage.googleapis.com/projects/serverless-com-demo' \
-XPOST $RUN_SERVICE_URL
```

**Comment by grant** [comment]
I'm seeing error in production too with Google Cloud.

```
TypeError: payload is null or undefined
```

I assure you, we're sending folks valid CloudEvents with the product.

**Comment by lance** [comment]
Looks like we are treating `data` as a required attribute. Feel free to contribute a fix as you are also a committer on the project. I will try and take a look today.

**Comment by lance** [comment]
> TypeError: payload is null or undefined
> How do you specify this? What do you mean? I tried adding a HTTP body with no luck.

Maybe you didn't do it right. I can assure you that sending a body with the request works. https://github.com/cloudevents/sdk-javascript/blob/master/test/integration/http_receiver_test.ts#L28-L40

**Comment by grant** [comment]
> It's not hard to find where this error is being thrown by using a simple unix command line tool called `grep`. It's here:

Hey mate, this is a bit snarky. Yes, I did find `src/parsers/json.ts`.

The point is that `data` is optional. Besides, our application shouldn't fail if we have a bad CE. It should just have `data` as undefined and not break the app.

**Comment by lance** [comment]
> Hey mate, this is a bit snarky. Yes, I did find src/parsers/json.ts.

Yeah, well :shrug:. If you found it you might have considered mentioning it in the PR instead of just saying "it's easier to just not use the SDK". If that's how you feel, as a maintainer of the project you could consider contributing a fix. Not really feeling the collaboration from you on this project.

**Comment by grant** [comment]
Sorry, I can't contribute more to this GitHub project at this time besides creating issues and using the library due to various reasons. I've tried multiple times and can't currently. I'm just saying that I can't use it and it's literally easier to continue not using it, not a feeling or judgement.

I've suggested a simpler project using TypeScript, focusing on core use-cases in the past. I'd imagine maybe 10 `src` files, simplifying the project, and deleting code that isn't useful for CE consumers. For me, I need to be able to consume a CloudEvent.

For a comparison, my colleague created the lightweight ruby SDK, which is what I'd expect in an ideal SDK:
https://github.com/cloudevents/sdk-ruby

**Comment by lance** [comment]
Again, if you think the project could be simplified and improved, you are more than welcome to contribute code or ideas. You are a committer on this project. I'm not sure exactly what you think the problem is, so beyond just abstract "it should be simpler" it would be beneficial to understand what you mean.

I'm not sure how much simpler this could be.

```js
import { CloudEvent, Receiver } from "cloudevents";

const receiver = new Receiver();
const event = receiver.accept(headers, body);
```

**Comment by grant** [comment]
> I'm not sure how much simpler this could be.
> 
> ```js
> import { CloudEvent, Receiver } from "cloudevents";
> 
> const receiver = new Receiver();
> const event = receiver.accept(headers, body);
> ```

I've created a new issue showing what should be improved: https://github.com/cloudevents/sdk-javascript/issues/261

I've been preparing for a video recording for a few weeks, but that's going to be done tomorrow so hopefully I can help shape this SDK. I appreciate the work and replies.
