### ISSUE TITLE
gts not found

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#263]
`gts` is used in the `tsconfig.json` but isn't installed or specified in the package.json.
This raises an error for tooling.

**Comment by grant** [comment]
Actually, this is only in the `typescript-ex` sample.
Not sure why we only have it there and not everywhere.

**Comment by lance** [comment]
Closing this for now since we don't use `gts`. If we choose to go that route, let's open another issue or PR that introduces its usage.
