### ISSUE TITLE
Remove All Version-Specific Methods

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#275]
**Describe the Bug**

This module includes a lot of public methods that assume there are are only 2 versions of the spec. We shouldn't copy-and-paste functions across versions. Rather, we should just pass a parameter to specify the CloudEvent version.

Here's an example:

## Actual

```ts
export function createV1(attributes: CloudEventV1Attributes): CloudEventV1 {
  const event: CloudEventV1 = {
    specversion: schemaV1.definitions.specversion.const,
    id: uuidv4(),
    time: new Date().toISOString(),
    ...attributes,
  };
  return new CloudEvent(event);
}

export function createV03(attributes: CloudEventV03Attributes): CloudEventV03 {
  const event: CloudEventV03 = {
    specversion: schemaV03.definitions.specversion.const,
    id: uuidv4(),
    time: new Date().toISOString(),
    ...attributes,
  };
  return new CloudEvent(event);
}
```

## Expected

```ts
export function create(attributes: CloudEventV03Attributes | CloudEventV1Attributes): CloudEvent {
  ...
  return new CloudEvent(event);
}
```

**Comment by lholmquist** [comment]
It looks like https://github.com/cloudevents/sdk-javascript/pull/277 addresses at least those 2 functions from above

**Comment by lance** [comment]
@lholmquist there are no other version specific functions that I am aware of being exported at the top level. I am closing this. @grant - If there are specific functions in nested files that should be addressed, please open a specific issue for them.

**Comment by grant** [comment]
Yup, looks good to close @lance.
