### ISSUE TITLE
A Cloudevent class per spec version

### ISSUE THREAD

**Issue by fabiojose** [cloudevents/sdk-javascript#28]
Today we have just one cloudevent.js that makes the interface with Spec classes. This is ok with vanilla js, because of flexibility which exists in js programming we inject new methods we needed.

Now it's time to stabilize the things. We are reaching the v1.0 and some attribute names are getting stable, in special the required ones: `id`, `source`, `specversion` and `type`.

We need:

- a base class with required attributes
- a class that extends the base one and makes specializations with it's own attributes
- every implementation MUST follow the [immutable object](https://en.wikipedia.org/wiki/Immutable_object) philosophy

**Comment by fabiojose** [comment]
@grant What do you think about this definition? May be would be better in ts?

```js
/*!
 * cloudevents.io
 * Apache-2.0 Licensed
 */

"use strict";

/**
 * CloudEvent prototype
 *
 * @example
 * let event = new CloudEvent("A234-1234-1234", "https://github.com/cloudevents/spec/pull", "com.github.pull.create", {
 *     "comexampleextension1" : "value",
 *     "comexampleextension2" : {
 *         "othervalue" : 5
 *     }
 * });
 *
 * @constructor
 * @class
 * @param {String} id - Identifies the event
 * @param {String} source - Identifies the context in which an event happened
 * @param {String} type - The originating occurrence
 * @param {Object} extensions - Custom additional context attributes

 * @param {Object} data - Data attribute
 * @public
 */
function CloudEvent(id, source, type, extensions, data) {

}

CloudEvent.prototype.data = (data) => {

};

/**
 * Returns the internal representation of context attributes, extension
 * attribute and data attribute.
 *
 * @example
 * let event = new CloudEvent("A234-1234-1234", "https://github.com/cloudevents/spec/pull", "com.github.pull.create");
 * event
 *   .then((payload) => {
 *     // use the event payload, which is valid
 *     payload.id;
 *     payload.source;
 *     payload.specversion;
 *   })
 *   .catch((err) => {
 *     // threat the err reporting an invalid payload
 *   });
 *
 * @return {Promise} To resolve the event as object notation
 * @public
 */
CloudEvent.prototype.asObject = () => {

};

/**
 * Validates the payload against the definitions, but if something
 * is wrong throws and exception.
 *
 */
CloudEvent.prototype.validate = () => {

};

module.exports = CloudEvent;
```

**Comment by grant** [comment]
Looks ok.
Would be much better with modern javascript (`class`) or TypeScript.

**Comment by fabiojose** [comment]
@grant Would like to help us with these definitions?

**Comment by grant** [comment]
@fabiojose Sent email to you to discuss more first.

**Comment by lance** [comment]
Given how the repo has evolved since this issue has been opened, I suggest closing this. @grant @fabiojose WDYT?

**Comment by fabiojose** [comment]
It's ok for me.

**Comment by lance** [comment]
@fabiojose OK closing for now - as things progress we may revisit this, or not. :)
