### ISSUE TITLE
Discussion: consider changing primary branch from 'master' to 'main'

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#283]
**Is your feature request related to a problem? Please describe.**
In an effort to be more inclusive as a community, and empathetic to those who may be affected by the term `master`, we should consider changing the primary branch of the repository to `main`. I have seen this happen in other projects, and I do not think that this will have an impact on current or potential contributors. To pre-emptively address rebuttals such as "this has nothing to do with master/slave that we see in other technical domains!", I'll refer you to an excellent post from the Gnome project where this change was discussed and made a year ago. https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html

**Describe the solution you would like to see**
Change the primary branch from `master` to `main`.

**Comment by lance** [comment]
@cloudevents/sdk-javascript-maintainers I'm going to make this change this week unless objected to here.

**Comment by grant** [comment]
Sounds good.

**Comment by lance** [comment]
@cloudevents/sdk-javascript-maintainers just a heads up. I will make this switch at the end of the day today.

**Comment by lance** [comment]
This is done
