### ISSUE TITLE
Release 2.0.3 with name change warning

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#291]
**Is your feature request related to a problem? Please describe.**
With the release of 3.0.0 under a different name (`cloudevents` instead of `cloudevents-sdk`), existing users of the 2.x versions will never receive an update or patch unless they know that the module name has changed, and make proactive steps to modify their dependencies.

In order to help smooth the transition for existing users, we should release a 2.0.3 patch version that emits a warning on install that there is a 3.0.x version out now with the new name. This won't guarantee that users see it, especially in automated systems, but it should help.

**Describe the solution you would like to see**
Issue a 2.0.3 release under the `cloudevents-sdk` name that includes a warning emitted during install that the name has changed to `cloudevents` and there is a new major version available.

**Comment by lholmquist** [comment]
+1

**Comment by lance** [comment]
Fixed in https://github.com/cloudevents/sdk-javascript/commit/9a91d87442611d52898e39df6fe85d4160362e0f
