### ISSUE TITLE
Don't Push Directly to Master

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#31]
I don't think we're allowed to push directly to `master`. It seems like we must get 1 reviewer cross company.

Wanted to create a PR to convert to TS, but the library was changing too often.
See https://github.com/cloudevents/sdk-javascript/issues/9
CC @n3wscott

**Comment by fabiojose** [comment]
@grant, yep! We are working with PR and reviews over that!

The library will change too often until we reach version `1.0`. After that, we expect to changeless.
