### ISSUE TITLE
Readme:  Supported Specification Features has broken links

### ISSUE THREAD

**Issue by lholmquist** [cloudevents/sdk-javascript#320]
**Describe the Bug**

If you were to click the v0.3 and v1.0 links on this table on the readme, https://github.com/cloudevents/sdk-javascript#supported-specification-features,  they return a 404 since they don't link anywhere.

We could/should probably link out to the appropriate section in the spec repo.

I did notice however, that the spec repo only has a master and v1.0 branches,  https://github.com/cloudevents/spec/branches/all so i'm not sure where to get the v0.3 spec links

**Comment by lance** [comment]
@lholmquist the v0.3 specs are just tagged https://github.com/cloudevents/spec/tree/v0.3
