### ISSUE TITLE
Typescript incompatible type in 3.1.0 and Express 4.x

### ISSUE THREAD

**Issue by aabrams** [cloudevents/sdk-javascript#340]
Trying to add in Express 4.x middleware: 

import { Receiver, CloudEvent } from "cloudevents";

	const receivedEvent: CloudEvent = Receiver.accept(req.headers, req.body);

It fails with:

(property) IncomingMessage.headers: IncomingHttpHeaders
Argument of type 'IncomingHttpHeaders' is not assignable to parameter of type 'Headers'.
  Index signatures are incompatible.
    Type 'string | string[]' is not assignable to type 'string'.
      Type 'string[]' is not assignable to type 'string'.ts(2345)

**Comment by lance** [comment]
It appears that the `IncomingHttpHeaders` type is from [Node core](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/ts3.1/http.d.ts#L7), so I think this will probably be a common issue. We should consider modifying our type.

https://github.com/cloudevents/sdk-javascript/blob/1fa3a05aed84bb4bdb225b3e2e11aba60d80efe8/src/message/index.ts#L21-L23

In the meantime @aabrams can you try

```js
const receivedEvent: CloudEvent = Receiver.accept(req.headers as Headers, req.body);
``

**Comment by aabrams** [comment]
Trying what you suggested (req.headers as Headers):

Argument of type 'Headers' is not assignable to parameter of type 'import("c:/Users/adam_a/repos/Segment-Webhook/node_modules/cloudevents/dist/transport/http/headers").Headers'.
  Index signature is missing in type 'Headers'.ts(2345)
Conversion of type 'IncomingHttpHeaders' to type 'Headers' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.ts(2352)
Conversion of type 'IncomingHttpHeaders' to type 'Headers' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'IncomingHttpHeaders' is missing the following properties from type 'Headers': append, delete, get, has, and 6 more.ts(2352)
