### ISSUE TITLE
Master and Main Branches?

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#356]
@lance @lholmquist I've noticed there are a bunch of branches on this repo, some which might be causing problems.

Specifically, having both a `master` and `main` might be causing issues, like PRs that are out of date. See https://github.com/cloudevents/sdk-javascript/pull/236 Could we delete stale branch `master`?

https://github.com/cloudevents/sdk-javascript/branches

**Comment by lance** [comment]
I think that should be OK - are there any release tags on that branch that we would lose though? I think that's the main thing to look out for.

**Comment by lholmquist** [comment]
i'm a +1 to removing master, to avoid the confusion.   Tags are just a pointer to a commit,  so i'm not sure what would happen,  but if that commit allow lives in the main branch,  then it should be fine? :shrug:

**Comment by lance** [comment]
> Tags are just a pointer to a commit, so i'm not sure what would happen, but if that commit allow lives in the main branch, then it should be fine? shrug

@lholmquist that was my thought as well. And anyway, several of us probably have that branch locally, so yes it should be OK.

**Comment by lholmquist** [comment]
+1  and is anything really ever deleted :)

**Comment by grant** [comment]
Thanks. I deleted the stale `master` branch.
