### ISSUE TITLE
Proposal for 4.0.0 Release

### ISSUE THREAD

**Issue by lholmquist** [cloudevents/sdk-javascript#359]
I noticed that we have a 3.2.0 release,  but the package.json is still at 3.1.0.  I think we did that release in a separate branch for some reason,  but the list of commits below were generated with `git log v3.1.0..upstream/main --oneline` and the "Changelog section" was generated from `npm run release -- --dry-run`

There are some spots in the code that say "remove in 4.0",  should we remove those things now before this release?

8205bc9 (HEAD -> main, upstream/main, origin/main) chore(package): Upgrade mocha from 7.1.2 to 8.2.0 (#354)
765b81c chore: tag v3.2.0 as release-v3.2.0 for release-please (#353)
c4afacb chore(ci,releases): bump release-please-action to 2.5.5 (#350)
f6be285 fix: extend Node.js IncomingHttpHeaders in our Headers type (#346)
1446898 fix: do not alter an event's data attribute (#344)
138de37 docs: update README with latest API changes (#347)
76688c4 chore: update release please to the latest release(2.4.1) (#345)
e334b6e feat: add emitterFactory and friends (#342)
a9114b7 chore: add an automated GH action for releases (#329)
eca43d9 fix: package.json & package-lock.json to reduce vulnerabilities (#338)
0a12146 docs: update README with maintainer names (#337)
1fa3a05 (remove-gts-from-ts-example) feat: add a constructor parameter for loose validation (#328)
7423acb fix: upgrade cloudevents from 3.0.1 to 3.1.0 (#335)
4779d89 chore(example): Replaced body parser with express JSON parser (#334)
6cd310c src(event)!: make the event's time property only a string (#330)
f3953a9 (lance/v3.2.x-backport, develop) feat: introduce Message, Serializer, Deserializer and Binding interfaces (#324)
17d4bc8 chore: add cucumber.js to list of files to lint and /docs to .gitignore (#327)
73f0bec chore: Update README with correct links for the support specification versions (#321)
0adcc35 chore: Remove commented version import. (#319)
6e2390e fix: upgrade uuid from 8.2.0 to 8.3.0 (#317)
4bf2eb8 chore: Update references of master to main (#316)
b5cf886 test: implement pending tests leftover from TS rewrite (#315)
8ac3eb0 refactor: validate cloudevent version agnostic (#311)
81623ac chore: typo (#313)
b3624c2 docs: add ref to CoC and other things (#244)

### ⚠ BREAKING CHANGES

* **event:** make the event's time property only a string (#330)

### Features

* add a constructor parameter for loose validation ([#328](https://github.com/cloudevents/sdk-javascript/issues/328)) ([1fa3a05](https://github.com/cloudevents/sdk-javascript/commit/1fa3a05aed84bb4bdb225b3e2e11aba60d80efe8))
* add emitterFactory and friends ([#342](https://github.com/cloudevents/sdk-javascript/issues/342)) ([e334b6e](https://github.com/cloudevents/sdk-javascript/commit/e334b6eceb0227196bacea6a843c268489a7b71b))
* introduce Message, Serializer, Deserializer and Binding interfaces ([#324](https://github.com/cloudevents/sdk-javascript/issues/324)) ([f3953a9](https://github.com/cloudevents/sdk-javascript/commit/f3953a9a5abf5c0267247f9939cf567a47eccd91))

### Bug Fixes

* do not alter an event's data attribute ([#344](https://github.com/cloudevents/sdk-javascript/issues/344)) ([1446898](https://github.com/cloudevents/sdk-javascript/commit/14468980f7a79da836bd3ee8304a8a5710a206c1))
* extend Node.js IncomingHttpHeaders in our Headers type ([#346](https://github.com/cloudevents/sdk-javascript/issues/346)) ([f6be285](https://github.com/cloudevents/sdk-javascript/commit/f6be285b8319919029d8c11f7bb49cac4bcc5c14))
* package.json & package-lock.json to reduce vulnerabilities ([#338](https://github.com/cloudevents/sdk-javascript/issues/338)) ([eca43d9](https://github.com/cloudevents/sdk-javascript/commit/eca43d907468dd07d9f291bb56f95f658f4b3c40))
* upgrade cloudevents from 3.0.1 to 3.1.0 ([#335](https://github.com/cloudevents/sdk-javascript/issues/335)) ([7423acb](https://github.com/cloudevents/sdk-javascript/commit/7423acb7fc4d431cc8d335fd5ccb1ad4a1f28a65))
* upgrade uuid from 8.2.0 to 8.3.0 ([#317](https://github.com/cloudevents/sdk-javascript/issues/317)) ([6e2390e](https://github.com/cloudevents/sdk-javascript/commit/6e2390ed6b3fa80474ce452581e52eeb13ffe995))

### Tests

* implement pending tests leftover from TS rewrite ([#315](https://github.com/cloudevents/sdk-javascript/issues/315)) ([b5cf886](https://github.com/cloudevents/sdk-javascript/commit/b5cf8865b98ae2b91407f4c5d90a7afd977ee96e))

### Documentation

* add ref to CoC and other things ([#244](https://github.com/cloudevents/sdk-javascript/issues/244)) ([b3624c2](https://github.com/cloudevents/sdk-javascript/commit/b3624c2b1a1df44df9b8094364c4db23242fc00e))
* update README with latest API changes ([#347](https://github.com/cloudevents/sdk-javascript/issues/347)) ([138de37](https://github.com/cloudevents/sdk-javascript/commit/138de3708463101e12428db6f456cfebf41a5093))
* update README with maintainer names ([#337](https://github.com/cloudevents/sdk-javascript/issues/337)) ([0a12146](https://github.com/cloudevents/sdk-javascript/commit/0a121465650ea2fac388a1df9c352a732ead0079))

### Miscellaneous

* **package:** Upgrade mocha from 7.1.2 to 8.2.0 ([#354](https://github.com/cloudevents/sdk-javascript/issues/354)) ([8205bc9](https://github.com/cloudevents/sdk-javascript/commit/8205bc96ae401099e0207bf387164fd955be7b33))
* tag v3.2.0 as release-v3.2.0 for release-please ([#353](https://github.com/cloudevents/sdk-javascript/issues/353)) ([765b81c](https://github.com/cloudevents/sdk-javascript/commit/765b81cdeca4bf425df7f37b49aa8ffed8b77513))
* **ci,releases:** bump release-please-action to 2.5.5 ([#350](https://github.com/cloudevents/sdk-javascript/issues/350)) ([c4afacb](https://github.com/cloudevents/sdk-javascript/commit/c4afacbad3e23cb9a9110984c14fd35859bfcd9c))
* add an automated GH action for releases ([#329](https://github.com/cloudevents/sdk-javascript/issues/329)) ([a9114b7](https://github.com/cloudevents/sdk-javascript/commit/a9114b712308efaca11c9e5f485948af5bb9e4bc))
* Remove commented version import. ([#319](https://github.com/cloudevents/sdk-javascript/issues/319)) ([0adcc35](https://github.com/cloudevents/sdk-javascript/commit/0adcc3532d8826254d4febfa2dc0b03dd4fe13b7))
* typo ([#313](https://github.com/cloudevents/sdk-javascript/issues/313)) ([81623ac](https://github.com/cloudevents/sdk-javascript/commit/81623ac443b7e68a595061357946a164edf446e6))
* Update README with correct links for the support specification versions ([#321](https://github.com/cloudevents/sdk-javascript/issues/321)) ([73f0bec](https://github.com/cloudevents/sdk-javascript/commit/73f0becc2b8e4f10ae40e23b77e4161d9b5ff611)), closes [#320](https://github.com/cloudevents/sdk-javascript/issues/320)
* update release please to the latest release(2.4.1) ([#345](https://github.com/cloudevents/sdk-javascript/issues/345)) ([76688c4](https://github.com/cloudevents/sdk-javascript/commit/76688c4c01554cbbad62ac1b719ef00c9328848b))
* **event:** make the event's time property only a string ([#330](https://github.com/cloudevents/sdk-javascript/issues/330)) ([6cd310c](https://github.com/cloudevents/sdk-javascript/commit/6cd310c14168013a4298f87fd8ec3ef51782d7ce))
* **example:** Replaced body parser with express JSON parser ([#334](https://github.com/cloudevents/sdk-javascript/issues/334)) ([4779d89](https://github.com/cloudevents/sdk-javascript/commit/4779d89ad054973cb0af8ec4119e073b78970392))
* add cucumber.js to list of files to lint and /docs to .gitignore ([#327](https://github.com/cloudevents/sdk-javascript/issues/327)) ([17d4bc8](https://github.com/cloudevents/sdk-javascript/commit/17d4bc85dfa9b8ecfcc3383c6154ed9aa2f37496))
* Update references of master to main ([#316](https://github.com/cloudevents/sdk-javascript/issues/316)) ([4bf2eb8](https://github.com/cloudevents/sdk-javascript/commit/4bf2eb838a32275433793e0692e32a373685f41e))
* validate cloudevent version agnostic ([#311](https://github.com/cloudevents/sdk-javascript/issues/311)) ([8ac3eb0](https://github.com/cloudevents/sdk-javascript/commit/8ac3eb0c69d980a4475052ce3f102b8b88602fa5))

**Comment by lholmquist** [comment]
@cloudevents/sdk-javascript-maintainers ^^

**Comment by grant** [comment]
The default branch has `3.1`, but the `v3.x` branch has `3.2`. So it's a bit weird seeing `3.2` out, yes.

I'm fine keeping the default branch up-to-date with whatever is published on npm (or a little ahead, but having github behind a bit weird imo).

**Comment by lholmquist** [comment]
i feel like we were going to release a 4.0 when we did the 3.2.0, but then we got delayed,  so things got a little weird.   but i can't remember that exactly.

but anyway,  the 4.0 release notes will have commits that are in the 3.2.0 release,  and i think that is ok,  since it is just documentation

**Comment by lance** [comment]
> i feel like we were going to release a 4.0 when we did the 3.2.0, but then we got delayed, so things got a little weird. but i can't remember that exactly.

There were a couple of issues that we wanted to definitively land in 4.0.0. IIRC

* https://github.com/cloudevents/sdk-javascript/issues/326 - done
* https://github.com/cloudevents/sdk-javascript/issues/332 - this is still open but we closed https://github.com/cloudevents/sdk-javascript/pull/349 without merging. Not sure what we want to do here
* https://github.com/cloudevents/sdk-javascript/issues/323 - I think we should address this issue

> but anyway, the 4.0 release notes will have commits that are in the 3.2.0 release, and i think that is ok, since it is just documentation

WFM

**Comment by lholmquist** [comment]
This https://github.com/cloudevents/sdk-javascript/pull/362 should also be merged first,  and possibly #360 which i will PR soon

**Comment by lance** [comment]
@lholmquist what do you say? About ready for that 4.0.0 release? (I could use it for boson).

**Comment by lholmquist** [comment]
@lance sorry,  some other things have gotten in the way.   I'll review what we have left today.

**Comment by lholmquist** [comment]
There are 2 issues that were mentioned that have not yet been fixed,  but I think they could be done in a follow up 4.0.1

#332
#323

Also the distributed tracing issue, #355 can be taken care of in a patch release


@lance if it is ok with you,  I think we can do this release.  The PR, #368 , that release-please created is pretty close,  but doesn't include all these changelog entries. I can update that PR manually, then merge it.  And hopefully it "fixes" our issues with the automation for next time



Below is the updated list of commits and changelog:


d656362 (HEAD -> main, upstream/main, origin/main) build(deps): bump highlight.js from 10.3.2 to 10.4.1 (#372)
79296a8 chore: add a transition guide.  fixes #360 (#363)
9f86cfd fix: improve error messages when validating extensions
132f052 fix: package.json & package-lock.json to reduce vulnerabilities
6adb578 ci: disable @typescript-eslint/no-explicit-any linter rule
43d9e01 feat: allow ensureDelivery to be able to ensure delivery on emit
d418a50 ci: add unit test for emitter
bda8581 docs: add Emitter logic example
25f9c48 feat: add EventEmitter to Emitter and singleton paradigm
875f700 feat!: Remove All API's that are labeled "Remove in 4.0" (#362)
8205bc9 chore(package): Upgrade mocha from 7.1.2 to 8.2.0 (#354)
765b81c chore: tag v3.2.0 as release-v3.2.0 for release-please (#353)
c4afacb chore(ci,releases): bump release-please-action to 2.5.5 (#350)
f6be285 fix: extend Node.js IncomingHttpHeaders in our Headers type (#346)
1446898 fix: do not alter an event's data attribute (#344)
138de37 docs: update README with latest API changes (#347)
76688c4 chore: update release please to the latest release(2.4.1) (#345)
e334b6e feat: add emitterFactory and friends (#342)
a9114b7 chore: add an automated GH action for releases (#329)
eca43d9 fix: package.json & package-lock.json to reduce vulnerabilities (#338)
0a12146 docs: update README with maintainer names (#337)
1fa3a05 (remove-gts-from-ts-example) feat: add a constructor parameter for loose validation (#328)
7423acb fix: upgrade cloudevents from 3.0.1 to 3.1.0 (#335)
4779d89 chore(example): Replaced body parser with express JSON parser (#334)
6cd310c src(event)!: make the event's time property only a string (#330)
f3953a9 (lance/v3.2.x-backport, develop) feat: introduce Message, Serializer, Deserializer and Binding interfaces (#324)
17d4bc8 chore: add cucumber.js to list of files to lint and /docs to .gitignore (#327)
73f0bec chore: Update README with correct links for the support specification versions (#321)
0adcc35 chore: Remove commented version import. (#319)
6e2390e fix: upgrade uuid from 8.2.0 to 8.3.0 (#317)
4bf2eb8 chore: Update references of master to main (#316)
b5cf886 test: implement pending tests leftover from TS rewrite (#315)
8ac3eb0 refactor: validate cloudevent version agnostic (#311)
81623ac chore: typo (#313)
b3624c2 docs: add ref to CoC and other things (#244)



## [4.0.0](https://github.com/cloudevents/sdk-javascript/compare/v3.1.0...v4.0.0) (2020-12-10)


### ⚠ BREAKING CHANGES

* Remove All API's that are labeled "Remove in 4.0" (#362)
* **event:** make the event's time property only a string (#330)

### Features

* add a constructor parameter for loose validation ([#328](https://github.com/cloudevents/sdk-javascript/issues/328)) ([1fa3a05](https://github.com/cloudevents/sdk-javascript/commit/1fa3a05aed84bb4bdb225b3e2e11aba60d80efe8))
* add emitterFactory and friends ([#342](https://github.com/cloudevents/sdk-javascript/issues/342)) ([e334b6e](https://github.com/cloudevents/sdk-javascript/commit/e334b6eceb0227196bacea6a843c268489a7b71b))
* add EventEmitter to Emitter and singleton paradigm ([25f9c48](https://github.com/cloudevents/sdk-javascript/commit/25f9c4860169a8ab576fba47791497ada3048d9f))
* allow ensureDelivery to be able to ensure delivery on emit ([43d9e01](https://github.com/cloudevents/sdk-javascript/commit/43d9e019720b7ddcc841117a7bbf97fff96e5e23))
* introduce Message, Serializer, Deserializer and Binding interfaces ([#324](https://github.com/cloudevents/sdk-javascript/issues/324)) ([f3953a9](https://github.com/cloudevents/sdk-javascript/commit/f3953a9a5abf5c0267247f9939cf567a47eccd91))
* Remove All API's that are labeled "Remove in 4.0" ([#362](https://github.com/cloudevents/sdk-javascript/issues/362)) ([875f700](https://github.com/cloudevents/sdk-javascript/commit/875f70017a09d1363c3f7eb2a5ea32eea1973e50))


### Bug Fixes

* do not alter an event's data attribute ([#344](https://github.com/cloudevents/sdk-javascript/issues/344)) ([1446898](https://github.com/cloudevents/sdk-javascript/commit/14468980f7a79da836bd3ee8304a8a5710a206c1))
* extend Node.js IncomingHttpHeaders in our Headers type ([#346](https://github.com/cloudevents/sdk-javascript/issues/346)) ([f6be285](https://github.com/cloudevents/sdk-javascript/commit/f6be285b8319919029d8c11f7bb49cac4bcc5c14))
* improve error messages when validating extensions ([9f86cfd](https://github.com/cloudevents/sdk-javascript/commit/9f86cfdf0efa014ccee385412836206763c65b96))
* package.json & package-lock.json to reduce vulnerabilities ([132f052](https://github.com/cloudevents/sdk-javascript/commit/132f052f1f64563a0dfc9b88056aa36a40f4c43f))
* package.json & package-lock.json to reduce vulnerabilities ([#338](https://github.com/cloudevents/sdk-javascript/issues/338)) ([eca43d9](https://github.com/cloudevents/sdk-javascript/commit/eca43d907468dd07d9f291bb56f95f658f4b3c40))
* upgrade cloudevents from 3.0.1 to 3.1.0 ([#335](https://github.com/cloudevents/sdk-javascript/issues/335)) ([7423acb](https://github.com/cloudevents/sdk-javascript/commit/7423acb7fc4d431cc8d335fd5ccb1ad4a1f28a65))
* upgrade uuid from 8.2.0 to 8.3.0 ([#317](https://github.com/cloudevents/sdk-javascript/issues/317)) ([6e2390e](https://github.com/cloudevents/sdk-javascript/commit/6e2390ed6b3fa80474ce452581e52eeb13ffe995))


### Tests

* implement pending tests leftover from TS rewrite ([#315](https://github.com/cloudevents/sdk-javascript/issues/315)) ([b5cf886](https://github.com/cloudevents/sdk-javascript/commit/b5cf8865b98ae2b91407f4c5d90a7afd977ee96e))


### Documentation

* add Emitter logic example ([bda8581](https://github.com/cloudevents/sdk-javascript/commit/bda85814649a0597909125914de51b3b4ca99aaa))
* add ref to CoC and other things ([#244](https://github.com/cloudevents/sdk-javascript/issues/244)) ([b3624c2](https://github.com/cloudevents/sdk-javascript/commit/b3624c2b1a1df44df9b8094364c4db23242fc00e))
* update README with latest API changes ([#347](https://github.com/cloudevents/sdk-javascript/issues/347)) ([138de37](https://github.com/cloudevents/sdk-javascript/commit/138de3708463101e12428db6f456cfebf41a5093))
* update README with maintainer names ([#337](https://github.com/cloudevents/sdk-javascript/issues/337)) ([0a12146](https://github.com/cloudevents/sdk-javascript/commit/0a121465650ea2fac388a1df9c352a732ead0079))


### Miscellaneous

* add a transition guide.  fixes [#360](https://github.com/cloudevents/sdk-javascript/issues/360) ([#363](https://github.com/cloudevents/sdk-javascript/issues/363)) ([79296a8](https://github.com/cloudevents/sdk-javascript/commit/79296a8e63b43325a51d7e6c9ba29d04066dee17))
* **package:** Upgrade mocha from 7.1.2 to 8.2.0 ([#354](https://github.com/cloudevents/sdk-javascript/issues/354)) ([8205bc9](https://github.com/cloudevents/sdk-javascript/commit/8205bc96ae401099e0207bf387164fd955be7b33))
* add an automated GH action for releases ([#329](https://github.com/cloudevents/sdk-javascript/issues/329)) ([a9114b7](https://github.com/cloudevents/sdk-javascript/commit/a9114b712308efaca11c9e5f485948af5bb9e4bc))
* tag v3.2.0 as release-v3.2.0 for release-please ([#353](https://github.com/cloudevents/sdk-javascript/issues/353)) ([765b81c](https://github.com/cloudevents/sdk-javascript/commit/765b81cdeca4bf425df7f37b49aa8ffed8b77513))
* **ci,releases:** bump release-please-action to 2.5.5 ([#350](https://github.com/cloudevents/sdk-javascript/issues/350)) ([c4afacb](https://github.com/cloudevents/sdk-javascript/commit/c4afacbad3e23cb9a9110984c14fd35859bfcd9c))
* Remove commented version import. ([#319](https://github.com/cloudevents/sdk-javascript/issues/319)) ([0adcc35](https://github.com/cloudevents/sdk-javascript/commit/0adcc3532d8826254d4febfa2dc0b03dd4fe13b7))
* typo ([#313](https://github.com/cloudevents/sdk-javascript/issues/313)) ([81623ac](https://github.com/cloudevents/sdk-javascript/commit/81623ac443b7e68a595061357946a164edf446e6))
* update release please to the latest release(2.4.1) ([#345](https://github.com/cloudevents/sdk-javascript/issues/345)) ([76688c4](https://github.com/cloudevents/sdk-javascript/commit/76688c4c01554cbbad62ac1b719ef00c9328848b))
* **event:** make the event's time property only a string ([#330](https://github.com/cloudevents/sdk-javascript/issues/330)) ([6cd310c](https://github.com/cloudevents/sdk-javascript/commit/6cd310c14168013a4298f87fd8ec3ef51782d7ce))
* **example:** Replaced body parser with express JSON parser ([#334](https://github.com/cloudevents/sdk-javascript/issues/334)) ([4779d89](https://github.com/cloudevents/sdk-javascript/commit/4779d89ad054973cb0af8ec4119e073b78970392))
* add cucumber.js to list of files to lint and /docs to .gitignore ([#327](https://github.com/cloudevents/sdk-javascript/issues/327)) ([17d4bc8](https://github.com/cloudevents/sdk-javascript/commit/17d4bc85dfa9b8ecfcc3383c6154ed9aa2f37496))
* Update README with correct links for the support specification versions ([#321](https://github.com/cloudevents/sdk-javascript/issues/321)) ([73f0bec](https://github.com/cloudevents/sdk-javascript/commit/73f0becc2b8e4f10ae40e23b77e4161d9b5ff611)), closes [#320](https://github.com/cloudevents/sdk-javascript/issues/320)
* Update references of master to main ([#316](https://github.com/cloudevents/sdk-javascript/issues/316)) ([4bf2eb8](https://github.com/cloudevents/sdk-javascript/commit/4bf2eb838a32275433793e0692e32a373685f41e))
* validate cloudevent version agnostic ([#311](https://github.com/cloudevents/sdk-javascript/issues/311)) ([8ac3eb0](https://github.com/cloudevents/sdk-javascript/commit/8ac3eb0c69d980a4475052ce3f102b8b88602fa5))

**Comment by lance** [comment]
> There are 2 issues that were mentioned that have not yet been fixed, but I think they could be done in a follow up 4.0.1

Agree that these two and #355 can be a part of 4.x.y

**Comment by lholmquist** [comment]
Version 4.0.0 just released on npm
