### ISSUE TITLE
Deprecation of Spec v0.1

### ISSUE THREAD

**Issue by fabiojose** [cloudevents/sdk-javascript#36]
Is time to deprecate the implementation for spec v0.1?

**Comment by grant** [comment]
Yes. I believe v0.1 is already dropped here.

**Comment by lance** [comment]
Remnants of it have been removed in https://github.com/cloudevents/sdk-javascript/pull/67

**Comment by lance** [comment]
@fabiojose I think this issue should be closed since #67 has been merged

**Comment by grant** [comment]
Cool. I'll close this issue.

@lance I would contact Dug on the CNCF Slack group to become a "SDK maintainer" in the cloudevents GitHub org so you can do things like directly close issues.

**Comment by duglin** [comment]
done!
