### ISSUE TITLE
CloudEvent Constructor Validation Error Too Generic

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#364]
**Describe the Bug**

Hi, I'm trying to debug an error from a different user. They're using this SDK.

Their code is like this:

```js
const respondEvent = new CloudEvent({
    type: 'dev.mink.apply.samples.divide',
    source: 'https://github.com/mattmoor/mink-apply-sample/divide',
    time: new Date(),
    dataContentType: 'application/json',
    data: { foo: 'bar' }
  });
```

However, running this produces the following output:

```
invalid extension name%                                                                                                                                                         
```

I think this output could be improved. I don't really know what is wrong and don't know if the user is really trying to create an extension.

- Ideally, the error would state the field name and exactly what is wrong with the key or value.
- Ideally, there's be no error (unless there's something really wrong with the data passed in, but it looks fine).

Workaround:

```js
const respondEvent = new CloudEvent({
    type: 'dev.mink.apply.samples.divide',
    source: 'https://github.com/mattmoor/mink-apply-sample/divide',
    time: new Date(),
    dataContentType: 'application/json',
    data: { foo: 'bar' }
  }, false);
```

**Steps to Reproduce**

```
curl -X POST \
-H 'Content-Type: application/json' \
-H 'ce-type: foo' \
-H 'ce-specversion: 1.0' \
-H 'ce-source: blah' \
-H 'ce-id: 1234' \
-d '{"a": 3, "b": 4}' localhost:8080
invalid extension name%              
```

Thanks!

**Comment by grant** [comment]
Relevant code:

https://github.com/cloudevents/sdk-javascript/blob/main/src/event/cloudevent.ts#L103

**Comment by lance** [comment]
The error is occurring because you are using `dataContentType` instead of `datacontenttype` for the property name and those properties are not the same thing. In the source you point to above, the regex is validating that the extension conforms to the spec and (all lowercase and a-z, 0-9). I agree that it would be useful to change that error to something like this however.

```js
        throw new ValidationError(`invalid extension name: ${key}`);
``` 

I would not recommend using the workaround (loose validation) if the intent is for this event to propagate to other systems, given that it is not valid.

**Comment by grant** [comment]
Thanks.

A nice error like in the spec would be good:

```
CloudEvent ValidationError("dataContentType"): CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. Attribute names SHOULD be descriptive and terse and SHOULD NOT exceed 20 characters in length.
```

https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention

**Comment by grant** [comment]
Would like to get feedback from event providers as to the strictness. I imagine some provider probably serves an event with a key >20 characters. Hopefully that doesn't break customer apps. I do see your point on the goal of keeping events clean when propagating.
