### ISSUE TITLE
Split SDK Functionality Into Separate Modules

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#367]
**Describe the Bug**

Different CloudEvent consumers have different uses/applications. Some features folks just want certain features. We talked about splitting this repo with separate modules:

> Here's the SDK spec: https://github.com/cloudevents/spec/blob/master/SDK.md

- CloudEvent object model / interfaces
- CloudEvent receiver
- CloudEvent emitter
- CloudEvent discovery / subscription

Same repo but separate libraries/modules.

**Comment by lance** [comment]
I don't think it makes sense to remove the transport APIs from the top level `cloudevents` module. I do think a `cloudevents-discovery` module and a `cloudevents-subscription` module are good though.

**Comment by grant** [comment]
> I don't think it makes sense to remove the transport APIs from the top level `cloudevents` module. I do think a `cloudevents-discovery` module and a `cloudevents-subscription` module are good though.

Agreed.

**Comment by grant** [comment]
I think this issue is a little old and outdated. I'm fine having it closed and all functionality together. Feel free to re-open it.
