### ISSUE TITLE
Deprecate cloudevents-sdk using npm deprecate

### ISSUE THREAD

**Issue by lholmquist** [cloudevents/sdk-javascript#369]
If you search for cloudevents in npm,  the cloudevents-sdk will still show up,  https://www.npmjs.com/package/cloudevents-sdk

I think we should run `npm deprecate` on that old version/name so it no longer shows up in the list,  and gets a nice banner added to it, if someone does find it,  like request has:  https://www.npmjs.com/package/request

Also this message will show when someone installs the old deprecated modules

**Comment by lance** [comment]
Sounds good to me. If you have the rights to do it, fire away!

**Comment by lholmquist** [comment]
i'll check,  and if i do,  i will take care of it

**Comment by lholmquist** [comment]
All Set:  https://www.npmjs.com/package/cloudevents-sdk
