### ISSUE TITLE
Use HTTP.structured() and/or HTTP.binary() in Express.js example

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#379]
**The Express.js example is only partially correct**

In the Express.js example, we are doing some things by hand that should really be handled by the framework. 

https://github.com/cloudevents/sdk-javascript/blob/6be3b2751401e529fce6ccf8a406a057472c10a9/examples/express-ex/index.js#L21-L41

In the response, we are just returning the `CloudEvent` instead of using the builtin framework capabilities. For example.

```
 const responseEventMessage = new CloudEvent({
        ...receivedEvent,
        source: '/',
        type: 'event:response'
    });
    // const message = HTTP.binary(responseEventMessage)
    const message = HTTP.structured(responseEventMessage)
    res.set(message.headers)
    res.send(message.body)
```

**Expected Behavior**

The example should more accurately represent the capabilities of the framework.

**Additional context**

See: https://stackoverflow.com/questions/65854143/how-to-write-knative-sequence-step

**Comment by lholmquist** [comment]
I agree,  we should review our examples to make sure they are up to date
