### ISSUE TITLE
SHOULD throw if extension attributes are NOT following naming convention?

### ISSUE THREAD

**Issue by c-pius** [cloudevents/sdk-javascript#380]
**Describe the Bug**
Extension attributes NOT following the naming convention (lowercase) are added to the event (no error thrown) but their value is added as `undefined`. 

**Steps to Reproduce**
Use the following snippet:
```js
const event = HTTP.toEvent({
  headers: {
    'Content-Type': 'application/json',
    'ce-id': '0815',
    'ce-specversion': '1.0',
    'ce-type': 'my.event.type',
    'ce-source': 'my.event.source',
    'ce-FOO': 'bar',
  },
  body: {}
})
```

Check the resulting event:
```js
{
  //...
  id: '0815',
  specversion: '1.0',
  type: 'my.event.type',
  source: 'my.event.source',
  foo: undefined
}
```

**Expected Behavior**
I assume according to [spec](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#attribute-naming-convention) an error should be thrown if attributes not following the naming convention are passed. Alternatively, if they are still accepted, their value should be passed on to the event correctly.

**Additional context**
If decided to still pass the extension attribute, I think the problem lies somewhere here:
https://github.com/cloudevents/sdk-javascript/blob/6be3b2751401e529fce6ccf8a406a057472c10a9/src/message/http/index.ts#L154

`header` has been sanitized (converted to lowercase, e.g. `ce-foo`) which is not present as such in the `headers` object (still original casing, e.g. `ce-FOO`) and therefore `undefined` is set as value.

**Comment by lance** [comment]
> I assume according to spec an error should be thrown if attributes not following the naming convention are passed. 

When creating a new event in code, I think I agree. But this is similar to other scenarios in that when receiving an event, the library should adhere to loose validation. That is, if we can effectively recover from the wrongly formatted event when receiving it, we should. I accept that this scenario should be caught and flagged somehow.

> Alternatively, if they are still accepted, their value should be passed on to the event correctly.

It's not so clear to me. In that case, the resulting event would not conform to the specification. I think I would rather see the event ultimately represented according to spec.

**Comment by lance** [comment]
> When creating a new event in code, I think I agree. 

In fact, that is what's happening. See: https://github.com/cloudevents/sdk-javascript/pull/389
