### ISSUE TITLE
plans for amqp/nats/stan/etc (similar to sdk-go)?

### ISSUE THREAD

**Issue by justinrush** [cloudevents/sdk-javascript#390]
**Is your feature request related to a problem? Please describe.**
The sdk-go project contains protocol implementations for other popular message buses, such as AMQP, NATS/STAN, and Kafka. I would like to see the same protocol layer available in the javascript SDK.

**Describe the solution you would like to see**
The same interfaces created for Protocol, Consumer, Receiver, Sender, etc, with a client class that leverages the interfaces. Bonus points if someone can write one or more of the protocol implementations for AMQP or Kafka.

**Additional context**
I'm working on a project that has a mix of typescript/javascript and golang based services using a mix of message transports. It would be great to standardize on something like cloudevents for the message format.

**Comment by lance** [comment]
Hi @justinrush - yes, we would definitely like to support all of the protocols that have a [specification](https://github.com/cloudevents/spec/#cloudevents-documents). There is no active work toward these goals at the moment, but we welcome contributions if you find yourself interested in that.

**Comment by Alexis01** [comment]
what about this request?

**Comment by LeoVS09** [comment]
@lance @justinrush @Alexis01 My team wants to use CoudEvents for our JS services, but currently, for transport, we use only Kafka. I made [cloudevents-kafka](https://github.com/LeoVS09/cloudevents-js-sdk-kafka) package as Kafka transport extension for the main `cloudevents` library, with all features which need for us right now. 
I do not have enough time to work on PR in this repository, but anyone who wants can use my package or copy it as PR in this repo.

**Comment by lholmquist** [comment]
once we do a new release with. #455 ,  can this be closed, or should we keep it open until those other protocols are dealt with?

**Comment by lance** [comment]
I think we can probably just close this, period. It's pretty broad and includes more than just transport implementations. The original ask is for all of the same interfaces here as in the Go SDK. But this implementation comes at it from a completely different perspective - not the least of which is the fact that Javascript is 'bring-your-own-transport-implementation' and Go just uses the built in HTTP under the hood to provide the implementation directly.

**Comment by lholmquist** [comment]
closing,  and if we need to re-open we can
