### ISSUE TITLE
Can not view the code quality and coverage metrics for this library. 

### ISSUE THREAD

**Issue by antonioaguilar** [cloudevents/sdk-javascript#400]
**Describe the Bug**
Codacy URLs for code quality and code coverage metrics are stale or not configure correctly

I clicked on the provided badge URLs on the README.md for this repo. 

https://www.codacy.com/app/fabiojose/sdk-javascript?utm_source=github.com&utm_medium=referral&utm_content=cloudevents/sdk-javascript&utm_campaign=Badge_Grade

https://www.codacy.com/app/fabiojose/sdk-javascript?utm_source=github.com&utm_medium=referral&utm_content=cloudevents/sdk-javascript&utm_campaign=Badge_Coverage

Got the following message from Codacy:
```
Something went wrong, we couldn't reach that repository
Could not find repository manual/fabiojose/sdk-javascript
```

**Steps to Reproduce**
1. click on code quality URL, or
2. click on code coverage URL

**Expected Behavior**
Should be able to view both code quality and coverage metrics for this open source library.

**Comment by lance** [comment]
Good catch - thanks. The correct link for both is https://app.codacy.com/manual/cloudevents/sdk-javascript/dashboard
