### ISSUE TITLE
CloudEvent omits `data` from console output

### ISSUE THREAD

**Issue by alex-dixon** [cloudevents/sdk-javascript#432]
**Describe the Bug**
Not sure this is a bug since it may be intentional, but I got lost trying to figure where my event data was until I saw it was defined as a getter and wasn't printing to the console.

**Steps to Reproduce**
1. console.log(myEvent) => headers
1. console.log(myEvent.data) => data

**Expected Behavior**

console.log(myEvent) => headers + data (❤️)

**Additional context**
node v14.17.1

**Comment by grant** [comment]
Maybe we need to add the data to the `toString` function here? Since `_data` is a private field in the class.

https://github.com/cloudevents/sdk-javascript/blob/2dc846c6594d2c19b0564a5e8394235aaa5c2713/src/event/cloudevent.ts#L153-L155

**Comment by lance** [comment]
> Maybe we need to add the data to the `toString` function here? Since `_data` is a private field in the class.

Actually, `event.toString()` _does_ print the data. It's just important to call `toString()`. The `toJSON()` function handles this.

https://github.com/cloudevents/sdk-javascript/blob/2dc846c6594d2c19b0564a5e8394235aaa5c2713/src/event/cloudevent.ts#L146-L151

Note below that to see the data, I must call `e.toString()`.

```
> node
Welcome to Node.js v16.6.1.
Type ".help" for more information.
> const { CloudEvent } = require('./dist')
undefined
> const e = new CloudEvent({ source: 'test', type: 'test', data: { message: 'hello' }})
undefined
> e
CloudEvent {
  id: 'a37ea91b-883e-4900-8d05-71aef2105d31',
  time: '2021-09-20T14:46:38.373Z',
  type: 'test',
  source: 'test',
  specversion: '1.0',
  datacontenttype: undefined,
  subject: undefined,
  datacontentencoding: undefined,
  dataschema: undefined,
  data_base64: undefined,
  schemaurl: undefined
}
> e.toString()
'{"id":"a37ea91b-883e-4900-8d05-71aef2105d31","time":"2021-09-20T14:46:38.373Z","type":"test","source":"test","specversion":"1.0","data":{"message":"hello"}}'
>
```

**Comment by grant** [comment]
I think I created a PR to fix the issue.
