### ISSUE TITLE
Does not support Batched Content Mode but does not fail with spec validation error

### ISSUE THREAD

**Issue by murrellrr** [cloudevents/sdk-javascript#440]
**Describe the Bug**
Spec allows for an array (or batch) of events to be submitted in the in Section: 4. JSON Batch Format at https://github.com/cloudevents/spec/blob/v1.0.1/json-format.md. If you pass the binding an array it quietly ignores it and just returns a CloudEvent object representing the first element of the array.

**Steps to Reproduce**
1. Create a HTTP request whose main body is an array of CloudEvent events JSON body = "[  {}, {}, {}  ]".

**Expected Behavior**
You could assume supporting batch is a "New Feature" and I would agree but I would assert ignoring it is a bug. Minimally should throw an TypeError letting the dev know this part of the spec (4. JSON Batch Format) is not supported?

**Additional context**
This is easily avoided by checking for an array first and then calling the constructor for each element but not intuitive with the  binding design accepting {header, body}, and lack of feedback at runtime is misleading.

**Comment by lance** [comment]
Thanks for submitting this issue! I have a couple of comments inline below.

> **Steps to Reproduce**
> 
> 1. Create a HTTP request whose main body is an array of CloudEvent events JSON body = "[  {}, {}, {}  ]".

I'm curious if you used the `application/cloudevents-batch+json` content type [noted in the spec](https://github.com/cloudevents/spec/blob/v1.0.1/http-protocol-binding.md#331-http-content-type). While I wouldn't expect it to work, the behavior you describe I would also not suspect! :) 

> **Expected Behavior** You could assume supporting batch is a "New Feature" and I would agree but I would assert ignoring it is a bug. 

The [SDK requirements](https://github.com/cloudevents/spec/blob/v1.0.1/SDK.md#technical-requirements) assert that an SDK must support "HTTP transport renderings in both structured and binary encodings" but remains silent about batch support. So, while I see your point, it's unrequired as of now.

> Minimally should throw an TypeError letting the dev know this part of the spec (4. JSON Batch Format) is not supported?

This would be reasonable behavior, imo.

**Comment by lance** [comment]
FWIW, I raised this issue in the CNCF Slack https://cloud-native.slack.com/archives/CCXF3CBL1/p1637098744022900

**Comment by lance** [comment]
@murrellrr I'm working on an implementation. Hopefully we can release support for batch mode relatively soon.

**Comment by lance** [comment]
@murrellrr batch support landed in 5.2.0. If you feel inclined, please give it a try and let us know how it goes.
