### ISSUE TITLE
The CloudEvent type should be generic

### ISSUE THREAD

**Issue by matthewrobertson** [cloudevents/sdk-javascript#445]
As a developer I usually know what the data payload of my cloudevent will be when I get my hands on it. It would be great if I could express this in typescript to enable better type checking and auto completion:

```
interface MyPayload {
  foo: string;
  bar: number;
}

const myHandler = (e: CloudEvent<MyPayload>) => {
  e.data.foo; // OK
  e.data.banana; // Type Error!
};
```
IMO the existing  type hint for the `data` field is not adding much value: https://github.com/cloudevents/sdk-javascript/blob/f7b2840f826be8294f5357ab3b9a530170148dfc/src/event/interfaces.ts#L129

This would be better expressed as something like:

```
export interface CloudEventV1OptionalAttributes<T> {
  // ...
  data?: T;
}
```

**Comment by lance** [comment]
@matthewrobertson thank you for the suggestion! I agree this is quite nice. While I feel pretty strong about my Node.js chops, please forgive my relative inexperience with TypeScript. (This project was converted to TS at the request of the community)

I just dropped a PR that should do what you want. IIUC this would not be a breaking from our mishmash type union. Can you please confirm that, and whether the PR accomplishes your aims. 

https://github.com/cloudevents/sdk-javascript/pull/446
