### ISSUE TITLE
Batched Content Mode

### ISSUE THREAD

**Issue by achille-roussel** [cloudevents/sdk-javascript#45]
Hello,

I wanted to ask if a plan to support [Batched Content Mode](https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#33-batched-content-mode) was in the work?

**Comment by fabiojose** [comment]
It's comming! But, could be faster if you help us with a nice PR!

**Comment by achille-roussel** [comment]
Fair point, I mostly didn’t want to duplicate work if it was already inflight. 

If I find time to contribute I’ll post on this issue 👍

**Comment by fabiojose** [comment]
Go ahead! We are looking forward for your PR.

**Comment by achille-roussel** [comment]
The HTTP bindings for CloudEvents are simple enough to implement that I ended up just writing custom code to support my use case instead of taking a dependency on this package, so I don't have much incentives to contribute to this package anymore.

Thanks for following up tho!

**Comment by lance** [comment]
@achille-roussel if you feel like submitting a pull request with support for batch mode, that would be great! For now, marking this as stalled and we can revisit as the SDK evolves.
