### ISSUE TITLE
Error handling response

### ISSUE THREAD

**Issue by MoMannn** [cloudevents/sdk-javascript#46]
I have a question regarding error handling of events. Standard dictates that you always return the event parameters(e.g. headers) in case of success what about in case of an error? In your example you do not return them but just respond with status 415.

And how to handle a batch of events if only one fails or n fail.

**Comment by xpepermint** [comment]
What I'd propose is something like this:

```
HTTP/1.1 200 OK
Content-Type: application/cloudevents+json; charset=utf-8
Content-Length: nnnn

{
    "specversion" : "1.0",
    "type" : "com.example.someevent",

    ... further attributes omitted ...

    "alerts" : [
       {
        "kind": "warning",
        "code": "1234"
     }
   ]
}
```

And for headers (similar to other HTTP headers):

```
HTTP/1.1 200 OK
ce-specversion: 1.0
ce-type: com.example.someevent
ce-time: 2018-04-05T03:56:24Z
ce-id: 1234-1234-1234
ce-source: /mycontext/subcontext
    .... further attributes ...
ce-alerts: warning:1234; ...
Content-Type: application/json; charset=utf-8
Content-Length: nnnn

NO RESPONSE
```

Alternatively, we can add `ce-status` attribute which holds `200/201` for success, `4xx` for application-level errors and `5xx` for system errors.

@fabiojose, @duglin do you guys think this is an acceptable approach? To support batch events we have to somehow include errors into CE definition part. Also returning `415` will not work for batch events - I'd always expect 200 on application-level alerts/exceptions.

**Comment by lance** [comment]
@MoMannn are you talking about event receivers and how they handle malformed events? I'm not sure I'm clear on what you are asking for.

**Comment by xpepermint** [comment]
@lance the question is how an error or errors should be returned by a service in a cloudevent manner.

**Comment by lance** [comment]
@xpepermint I think this might be most appropriately discussed on the cloudevents/spec repo in #566. Whatever decisions are made there will roll down to all of the SDKs. Unless there is something specific to this repo, this should probably be closed and handled there.
