### ISSUE TITLE
Validation is broken

### ISSUE THREAD

**Issue by adgerrits** [cloudevents/sdk-javascript#500]
**Describe the Bug**
Event.validate() is not functioning correct (tested in the express-ex example)

**Steps to Reproduce**
1. let e = HTTP.toEvent({headers: req.headers,body: { "a space": "not allowed", specversion: "1.0", source: "source1", id: "1", type: "test" }
2. e.validate() //no error

**Expected Behavior**
An error (just like when an ext.attribute with the name "Acapital"  is used).

**Additional context**
The problem seems to lie in [spec.ts](https://github.com/cloudevents/sdk-javascript/blob/main/src/event/spec.ts) because of a broken reference tot the v1-schema. Looks as if it's there since release 5.4.0 when a separate schema-folder was created.

**Comment by lance** [comment]
> The problem seems to lie in [spec.ts](https://github.com/cloudevents/sdk-javascript/blob/main/src/event/spec.ts) because of a broken reference tot the v1-schema. Looks as if it's there since release 5.4.0 when a separate schema-folder was created.

I know it seems that way, but the schema is actually precompiled at build time, so you don't see it in this source repository. You can see where this was changed here: https://github.com/cloudevents/sdk-javascript/pull/471 and where it actually happens during the build here: https://github.com/cloudevents/sdk-javascript/blob/847f6bfcc77934a53b07493a957ed11f724c6deb/package.json#L10

This seems like a genuine bug in the validation code. Extensions, unfortunately, do not have a formalized JSON spec that we can use to generate a validator (pretty sure about that). You can see in the CloudEvent spec that it does not mention extensions: https://github.com/cloudevents/spec/blob/main/cloudevents/formats/cloudevents.json. Thanks for reporting this.
