### ISSUE TITLE
Does not work in browsers as of 5.3.1

### ISSUE THREAD

**Issue by cbrianball** [cloudevents/sdk-javascript#525]
**Describe the Bug**
Based on other issues in this repo and some of the examples, it looks like this package is expected to work in the browser. Using any version after 5.3.0, there is an error in the browser console with the text "process is not defined".

**Steps to Reproduce**
1. Create website project (e.g., `npm create vite@latest`)
2. Install any version of cloudevents > 5.3.0
3. Add `import { CloudEvent } from "cloudevents"` to a javascript file (and use it to ensure tree shaking doesn't remove the code).
4. Run the application
5. Note in the browser console, the error "process is not defined"

The issue appears to be caused by the `util` dependency introduced in 5.3.1.

**Expected Behavior**
cloudevents NPM package should work inside the browser.

**Comment by lholmquist** [comment]
I've reproduced the error using the websocket example

Looks like this is an issue in the util package when using webpack 5,  https://github.com/browserify/node-util/issues/57#issuecomment-764436352

i have a fix that i'll PR in a little later
