### ISSUE TITLE
Add Test Runner for Node 18 LTS

### ISSUE THREAD

**Issue by OneCricketeer** [cloudevents/sdk-javascript#532]
README says LTS Node versions are supported. Yet, Node 18 LTS is untested for pull-requests. 

**Describe the solution you would like to see**
Would like to see Node v18 tests running and passing.

**Additional context**
Maybe 12 should be removed? https://nodejs.dev/en/about/releases/

**Comment by lholmquist** [comment]
> Maybe 12 should be removed?

Totally agree.  Node 14 also goes EOL at the end of April,  so maybe we should wait until then, so we only have to do 1 major version bump.
