### ISSUE TITLE
Invalid default data for parsing in binary mode

### ISSUE THREAD

**Issue by cardil** [cloudevents/sdk-javascript#538]
**Describe the Bug**
When parsing a CE from HTTP binary message, this library fails to parse the CE correctly. It uses a `{}` as a default value for data, even if data isn't given, nor have content type like `text/plain`.

**Steps to Reproduce**
1. Parse CE from HTTP:
   ```js
   const ce = HTTP.toEvent({ headers: req.headers, body: req.body })
   ```
1. Send an HTTP like:
   ```http
   POST /events HTTP/1.1
   Content-Length: 0
   Host: localhost:8080
   ce-id: xuPh9kai
   ce-source: local
   ce-specversion: 1.0
   ce-type: ping
   content-type: text/plain
   ```

**Actual Behavior**
The event is parsed incorrectly into (notice the `{}` in data):

```json
{
  "id": "xuPh9kai",
  "time": "2023-04-19T10:04:25.088Z",
  "type": "ping",
  "source": "local",
  "specversion": "1.0",
  "datacontenttype": "text/plain",
  "data": {}
}
```

**Expected Behavior**
The event should be parsed correctly into:

```json
{
  "id": "xuPh9kai",
  "time": "2023-04-19T10:04:25.088Z",
  "type": "ping",
  "source": "local",
  "specversion": "1.0",
  "datacontenttype": "text/plain",
  "data": ""
}
```

**Additional context**

This incorrect parsing prevents interoperation with other languages. For example, in https://github.com/openshift-knative/showcase/pull/24, I use a Rust built WASM module (using _cloudevents-rust_ lib) to print the given CE as structured JSON.

/kind bug

**Comment by cardil** [comment]
Hmm, this is even worse. Sending request like:

```http
POST /events HTTP/1.1
Content-Length: 12
Host: localhost:8080
ce-id: Kea7feem
ce-source: local
ce-specversion: 1.0
ce-type: ping
content-type: test/plain

Hello World!
```

Results in the following CE:

```json
{
  "id": "Kea7feem",
  "time": "2023-04-20T13:01:34.972Z",
  "type": "ping",
  "source": "local",
  "specversion": "1.0",
  "datacontenttype": "test/plain",
  "data": {}
}
```

It should be (data is missing, despite having content type of `test/plain`):

```json
{
  "id": "Kea7feem",
  "time": "2023-04-20T13:01:34.972Z",
  "type": "ping",
  "source": "local",
  "specversion": "1.0",
  "datacontenttype": "test/plain",
  "data": "Hello World!"
}
```

**Comment by lance** [comment]
@cardil I am not able to recreate this issue. This module does not actually implement a server that receives incoming requests - that is up to the users of the module. However, we do have extensive tests around incoming CloudEvent data. For example, see this test for `text/plain`.

https://github.com/cloudevents/sdk-javascript/blob/1cf8f8acae6678ab62b25f82cc11f0e756d87a5c/test/integration/message_test.ts#L116-L127

The `[faas-js-runtime](https://github.com/nodeshift/faas-js-runtime)` module, however does implement a server and parses incoming CloudEvents, for which there are also tests. For example, here we test your specific use case:

https://github.com/nodeshift/faas-js-runtime/blob/deb9f99444630eb440ea1d270e73ea47b4c745a1/test/test-http-body.js#L52-L71

Can you provide some code that enables me to reproduce this locally?

**Comment by lance** [comment]
@cardil I took a look at the showcase app and I believe the problem is in your app. Specifically, the `/events` endpoint is not configured for `text/plain` only for `application/json` see here: https://github.com/openshift-knative/showcase/blob/ad31193312c61458de0380979fb038d0db13001e/expressjs/src/routes/events/endpoint.js#L22-L34 and here: https://github.com/openshift-knative/showcase/blob/ad31193312c61458de0380979fb038d0db13001e/expressjs/src/routes/events/endpoint.js#L78-L99

**Comment by cardil** [comment]
I think you are right @lance!

I think this Express middleware automatically parses everything as JSON: https://github.com/openshift-knative/showcase/blob/latest/expressjs/src/middleware/json.js#L7

Ref.: https://www.geeksforgeeks.org/express-js-express-json-function

I'll confirm it, and close this issue.

Probably, the Express JSON middleware should NOT parse the body, if the content type isn't JSON.

**Comment by lance** [comment]
> I think this Express middleware automatically parses everything as JSON: https://github.com/openshift-knative/showcase/blob/latest/expressjs/src/middleware/json.js#L7

Yes I think you are right. You might consider using `express.raw()`.

**Comment by lance** [comment]
@cardil have you been able to confirm this assessment on your end?

**Comment by lance** [comment]
@cardil based on your PR here https://github.com/openshift-knative/showcase/pull/25 I am assuming you have resolved this issue on your end. If you still find that there is an issue, please reopen this one or start a new one.
