### ISSUE TITLE
Compatible with Node 20.x

### ISSUE THREAD

**Issue by w3nl** [cloudevents/sdk-javascript#553]
**Is your feature request related to a problem? Please describe.**
You receive a warning in e.g. Node 20.1.0 and 20.2.0

**Describe the solution you would like to see**
Change the compatible engines to all Node 20 versions
See: https://github.com/cloudevents/sdk-javascript/pull/552

**Additional context**
Current:
```
"engines": {
    "node": ">=16 <=20.0.0"
  }
```

**Comment by lholmquist** [comment]
merged #552
