### ISSUE TITLE
Unable to retrieve data from the HTTP request

### ISSUE THREAD

**Issue by jianzs** [cloudevents/sdk-javascript#567]
**Describe the Bug**
I utilize Knative RedisStreamSource to distribute events. These events are then received and processed by express.js, and parsed using cloudevents SDK. However, the parsing result only includes attributes without any data.

At the same time, I can successfully retrieve data using [event-display](https://github.com/knative/eventing-contrib/blob/main/cmd/event_display/main.go) written with go-based SDK.

**Steps to Reproduce**
1. deploy the deployment and service of cloudevent receiver
2. deploy RedisStreamSource.
3. XADD new data to Redis.
4. watch the log of Pod.

**Expected Behavior**

Get cloudevent data from HTTP Request using TypeScript.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

TypeScript not working.
![image](https://github.com/cloudevents/sdk-javascript/assets/20160766/c57f6805-aadb-40dd-addb-a6fcd3bb15d8)

But, Go works well.
![image](https://github.com/cloudevents/sdk-javascript/assets/20160766/25e4aa29-fa13-49d6-bc98-061dc67e575b)

**Comment by lance** [comment]
Hi @jianzs in your TypeScript example, can you please print the `req.headers` and `req.data` values?

**Comment by jianzs** [comment]
> Hi @jianzs in your TypeScript example, can you please print the `req.headers` and `req.data` values?

Thank you for your suggestion. I have identified the reason for the issue. By default, Express.js does not parse the request body...

**Comment by lance** [comment]
> > Hi @jianzs in your TypeScript example, can you please print the `req.headers` and `req.data` values?
> 
> Thank you for your suggestion. I have identified the reason for the issue. By default, Express.js does not parse the request body...

Excellent - that's what I was hoping you'd say :)

**Comment by abdennour** [comment]
very upset about the buggy sdk with node/js .. while other prg. lg works fine

**Comment by lance** [comment]
> very upset about the buggy sdk with node/js .. while other prg. lg works fine

Your contributions towards fixes will be welcome!
