### ISSUE TITLE
Recommend dropping support for 0.2

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#61]
In the [SDK requirements documentation](https://github.com/cloudevents/spec/blob/master/SDK.md#contribution-acceptance), it says "Each SDK supports the latest(N), and N-1, major releases of the CloudEvent spec", with a special case being 1.0 as latest with 0.3 recommended support.

Ultimately, dropping support for 0.2 should make maintenance simpler. From npm download numbers, I guess it's hard to tease out how many are still on 0.2, but this seems reasonable.

I wonder also what the versioning strategy is. Is the npm module is versioned independently from the spec version? It seems like it must be - at least for minor and patch levels.

**Comment by grant** [comment]
I agree in dropping 0.2 (and I support dropping 0.3).

**Comment by helio-frota** [comment]
+1 in dropping support for 0.2

**Comment by lance** [comment]
@grant currently, it is recommended that adapters continue to support v0.3. See: https://github.com/cloudevents/spec/blob/master/SDK.md#contribution-acceptance

**Comment by lance** [comment]
Hmm - although it appears that 0.3 isn't really supported. https://github.com/cloudevents/sdk-javascript/blob/master/lib/cloudevent.js#L1-L7

**Comment by grant** [comment]
> @grant currently it is recommended that adapters continue to support v0.3. See: https://github.com/cloudevents/spec/blob/master/SDK.md#contribution-acceptance

I propose we follow the versioning of the most mature CE SDK, Go, and support v1 and v2.
https://github.com/cloudevents/sdk-go

However, this library needs a bit of work before then.

**Comment by fabiojose** [comment]
+1
