### ISSUE TITLE
Add grant as collaborator

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#64]
Hello, I'd like to become a copaborator for this repo as I'm working heavily on events at Google.
I was requested to create an issue, so here it is!

**Comment by fabiojose** [comment]
LGTM

@duglin ?

**Comment by grant** [comment]
I've sent a Slack message and email to Dug for this request.

**Comment by duglin** [comment]
sorry for the delay - Should be done now

**Comment by grant** [comment]
Sorry @duglin, can I have write access like fabiojose? I can't see any changes in functionality. I'd like to merge approved PRs and manage issues if needed.

**Comment by duglin** [comment]
hmmm did you accept the invite?  The team had write access, but I just upped it to admin

**Comment by grant** [comment]
Oh, I see you added me to the org. That works even better!
GitHub didn't notify me. Anyways, it all works.
