### ISSUE TITLE
Unnecessary `ext` folder

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#69]
The repo has a folder of the CE spec in JSON format in `ext`.

https://github.com/cloudevents/sdk-javascript/tree/master/ext

While this may be useful, it's not necessary for a CloudEvent SDK. Let's refer back to the spec rather than keeping the files.

**Comment by grant** [comment]
It looks like these specs might be currently used. I'll keep this open but close the PR.

**Comment by lance** [comment]
This issue is related to https://github.com/cloudevents/sdk-javascript/issues/96. The .json in `ext/` is used to  validate the data in an event using the AJV validator. I don't think this should be removed.

**Comment by grant** [comment]
Yes, it shouldn't be removed unless there is a replacement validator.

**Comment by lance** [comment]
Closing. Fixed in https://github.com/cloudevents/sdk-javascript/pull/129
