### ISSUE TITLE
$ref: keywords ignored in schema at path "#"

### ISSUE THREAD

**Issue by micheleangioni** [cloudevents/sdk-javascript#7]
Hi,
just requiring the sdk with a simple
`const Cloudevent = require('cloudevents-sdk');`

causes the following error to be shown in the console:

`$ref: keywords ignored in schema at path "#"`

Any suggestion or comment?

**Comment by fabiojose** [comment]
@micheleangioni any other detail? Are you using in frontend running in the browser?

**Comment by micheleangioni** [comment]
@fabiojose I am pretty sure it's related to the `ajv` library. I think something is wrong in the json schema definition.
However, I use it in Node.js.

**Comment by fabiojose** [comment]
Hi @micheleangioni, according with [this](https://github.com/epoberezkin/ajv/blob/master/lib/dot/validate.jst#L152) this is a warn message.

What do you think? In my option this is not big problem.

Should we close this?

**Comment by micheleangioni** [comment]
Hey @fabiojose , no, it's not a big problem. It's just that if all libraries emitted a warning line, an application would be flooded by warnings at startup.

What I mean it's that, even if it does not cause problems, it would be nice to remove the warning somehow. I would leave it open honestly, at least for now.

**Comment by fabiojose** [comment]
Solve with PR #10
