### ISSUE TITLE
Integrate with conformance cucumber tests

### ISSUE THREAD

**Issue by lance** [cloudevents/sdk-javascript#71]
The cloudevents/conformance repository now has HTTP transport [cucumber specifications](https://github.com/cloudevents/conformance/blob/master/features/http-protocol-binding.feature). This SDK should integrate these into the tests. 

Ref: https://github.com/cucumber/cucumber-js

**Comment by helio-frota** [comment]
Going to assign that to me and start playing with. In case things get delayed (until next week) I remove the assignment :+1:

**Comment by helio-frota** [comment]
removing the assignment. I can revisit if needed later, also short week for me here.
