### ISSUE TITLE
Travis is Flaky

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#81]
Travis looks like it is flaky. I have added some PRs that don't affect the tests, yet Travis seems to fail.

Example:
https://github.com/cloudevents/sdk-javascript/pull/74

Ideally a PR like this shouldn't fail.

**Comment by lance** [comment]
I think this will be resolved with https://github.com/cloudevents/sdk-javascript/pull/78

**Comment by grant** [comment]
Hi, can we please keep the issue open until we're sure the issue is fixed? Did we test that this is fixed?
I'm still seeing the issue.

Here is trace from a test I ran after the PR merged:

```
> cloudevents-sdk@1.0.0 coverage-publish /home/travis/build/cloudevents/sdk-javascript
> wget -qO - https://coverage.codacy.com/get.sh | sh -s report -l JavaScript -r coverage/lcov.info
sh: 3: set: Illegal option -o pipefail
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cloudevents-sdk@1.0.0 coverage-publish: `wget -qO - https://coverage.codacy.com/get.sh | sh -s report -l JavaScript -r coverage/lcov.info`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cloudevents-sdk@1.0.0 coverage-publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-04-29T16_16_53_094Z-debug.log
The command "if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run coverage-publish; else npm test; fi" exited with 2.
cache.2
store build cache
```

**Comment by lance** [comment]
Not sure where that failure is happening now. Can you link to it? All of the recent CI runs for pull requests are passing: https://travis-ci.org/github/cloudevents/sdk-javascript/pull_requests

And the CI run for #78 passed: https://travis-ci.org/github/cloudevents/sdk-javascript/builds/681089567. 

It seems the failure is only happening on your branches. Maybe you haven't pulled that commit in yet?

Also - I'm curious... Why are you creating fix branches on upstream and not on your own fork?

**Comment by lance** [comment]
> Also - I'm curious... Why are you creating fix branches on upstream and not on your own fork?

This also makes me wonder if it really makes sense for the Travis-CI configuration to build all branches. Perhaps it should be [configured](https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches) to build only from `master` and any release branches. (Speaking of... it would probably make sense to create release branches).

**Comment by lance** [comment]
@grant - looks like you got the CI issues worked out. OK to close this now?

**Comment by grant** [comment]
Looks like it's been fixed and the signing issue isn't a problem anymore. Thanks for checking. Closing.
