### ISSUE TITLE
Remove "Fun" Functions

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#82]
This SDK has a set of common utility methods in a file called `fun.js`:
https://github.com/cloudevents/sdk-javascript/blob/master/lib/utils/fun.js

These methods are common amongst other libraries and shouldn't be re-invented.
Rather, use a library such as `is`:
https://www.npmjs.com/package/is

**Comment by fabiojose** [comment]
+1

**Comment by lance** [comment]
I agree that a file full of utility functions can be a code smell. But I generally prefer to keep dependencies as minimal as possible. What's the benefit of removing this code that already exists and works and replacing it with a dependency?

**Comment by grant** [comment]
> What's the benefit of removing this code that already exists and works and replacing it with a dependency?

The less code we have to maintain the faster we can progress with testing, refactoring, updating etc. We have a lot of code that is not needed. There are a lot of reasons to use libraries and simplify functions.

I think the reality is that we'll include one dependency for type validation and remove all the unused code.

**Comment by lance** [comment]
> The less code we have to maintain the faster we can progress with testing, refactoring, updating etc.

I generally agree that less is more. I'm just saying that this works, it's 1/30 the size of the `is` module, and I haven't seen any indication that maintaining this single file is problematic for our velocity. To me, switching to `is` seems arbitrary, bloats the install size of the module, and doesn't really buy us anything.
