### ISSUE TITLE
Question: To separate constants by meaning/group ?

### ISSUE THREAD

**Issue by helio-frota** [cloudevents/sdk-javascript#92]
For example `STRUCTURED_ATTRS_1` is used only inside `received_structured_1.js`.
But it requires all the other constants inside: `require("./constants.js");`.

Is it worth separating constants in different files? Is there a possibility that the file of constants will grow even more?

**Comment by fabiojose** [comment]
I guess not, no way to constants.js grow up.

**Comment by helio-frota** [comment]
@fabiojose thanks for the quick response, the current size of the file is acceptable :+1: 
only concern is in case that increase the size to the point of start losing meaning.

**Comment by fabiojose** [comment]
Now the spec will change less frequently, no more huge changes like we have from 0.1, .3 and 1.0
