### ISSUE TITLE
Recommend dropping support for 0.3 in Favor of 1.0 (and 2.0)

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-javascript#99]
I recommend we drop support for 0.3 events and only support the major releases of the CloudEvent spec. 0.3 is not a major release. There is no other major release. [See releases](https://github.com/cloudevents/spec/releases).

See go for example (v1 and v2):
https://github.com/cloudevents/sdk-go

> Each SDK supports the latest(N), and N-1, major releases of the CloudEvent spec*.
> Within the scope of a major release, only support for the latest minor version is needed.

If there's still debate as to the exact definition of this, but I propose we talk to the other SDK folks if there's really.

I don't think there are many users of this library that it should be a problem.

---

It would be dramatically easier to refactor this library and improve the experience if 0.3 wasn't here.

**Comment by helio-frota** [comment]
That makes sense. :+1: 

"Better code is no-code"... without v0.3 I don't need to bother with a failing test anymore: https://github.com/cloudevents/sdk-javascript/pull/95

**Comment by helio-frota** [comment]
npm has no support of download counts per version.

So we can only speculate on that:

Comparing downloads from ~6 months https://www.npmjs.com/package/cloudevents-sdk/v/0.3.2
https://npm-stat.com/charts.html?package=cloudevents-sdk&from=2019-10-01&to=2020-04-29

And looking the public projects that are using cloudevents-sdk:

https://github.com/micheleangioni/node-messagebrokers/blob/master/package.json#L52
https://github.com/boson-project/faas-js-runtime/blob/master/package.json#L22
https://gitlab.com/hahnpro/flow-sdk/-/blob/master/package.json#L32
https://github.com/joshwlewis/neverred-function/blob/master/package.json#L18

Some of repositories listed on npm as dependents are deprecated and/or 404.

/cc @lance

**Comment by lance** [comment]
Just to be clear. There is no 2.0 version of the spec. The only two versions that are expected to be supported are 1.0 and (semi-optionally) 0.3. FWIW, the Go module does support both of these versions.

> [Note: Supported CloudEvents specification: [0.3, 1.0].](https://github.com/cloudevents/sdk-go/blob/master/README.md#working-with-cloudevents)

So even though I said yesterday that I agreed dropping 0.3 would make refactoring easier. I'm still on the fence about it.

**Comment by grant** [comment]
> So even though I said yesterday that I agreed dropping 0.3 would make refactoring easier. I'm still on the fence about it.

Yeah, I can see that.

At the very least, we should be able to refactor this library such that removing 0.3 would be easy.

I think the cost-benefit of removing 0.3 in favor of an awesome SDK for 1.0+ would be great. Perhaps we can support 0.3 events without having completely separate files for each file (`..._0_3.js) in this library.

**Comment by grant** [comment]
@lance @fabiojose LMK what your thoughts are here. I can definitely see both sides and respect the previous work here.

I was going to wait for your feedback here and for this issue to be resolved before making other PRs that might conflict.

**Comment by lance** [comment]
I would like to propose closing this issue until 2.0 is released in order to remain as spec compliant as possible.

**Comment by grant** [comment]
> I would like to propose closing this issue until 2.0 is released in order to remain as spec compliant as possible.

Sounds good. Looking at the Go SDK and spec, we should support 0.3 events still.

I think there should be some simplification to this SDK, but not dropping it is OK.
